var bingoList = [
[
{ "name": "防寒着", "en": "Warm Doublet", "types": [ "Clothes", "Cold Resistance", "Hateno" ] },
{ "name": "“錆びた”武器入手", "en": "Any 'Rusty' Equipment item", "types": [ "Equipment" ] },
{ "name": "始まりの塔エリア コログのミ 3個", "en": "3 Great Plateau Koroks", "types": [ "Plateau Korok", "Plateau" ] },
{ "name": "ハイリアのズボン", "en": "Hylian Trousers", "types": [ "Clothes", "Hylian Gear", "Rupee" ] },
{ "name": "“ボコ”系武器入手", "en": "Any 'Boko' Equipment item", "types": [ "Equipment" ] },
{ "name": "しのび系料理", "en": "Any Sneaky meal", "types": [ "Cooking" ] },
{ "name": "がんばり系料理", "en": "Any Energizing meal", "types": [ "Cooking", "Stamina" ] },
{ "name": "微妙な料理", "en": "Dubious Food", "types": [ "Cooking" ] },
{ "name": "ピリ辛系料理", "en": "Any Spicy meal", "types": [ "Cooking", "Cold Resistance" ] },
{ "name": "硬すぎ料理", "en": "Rock-Hard Food", "types": [ "Cooking" ] }
], [
{ "name": "ゴーゴー薬", "en": "Hasty Elixir", "types": [ "Cooking" ] },
{ "name": "漁師のモリ", "en": "Fishing Harpoon", "types": [ "Equipment" ] },
{ "name": "甘露煮肉", "en": "Glazed Meat", "types": [ "Cooking" ] },
{ "name": "ガーディアンランス (+付きも可)", "en": "Any Guardian Spear", "types": [ "Equipment", "Guardian" ] },
{ "name": "ガーディアンナイフ (+付きも可)", "en": "Any Guardian Sword", "types": [ "Equipment", "Guardian" ] },
{ "name": "マモノに襲われている旅人を助ける", "en": "Save a Traveler in Peril", "types": [ "Monster" ] },
{ "name": "ボコ拠点の宝箱を2個開く", "en": "Open 2 Bokoblin Camp Chests", "types": [ "Plateau" ] },
{ "name": "ゴーゴー系料理", "en": "Any Hasty meal", "types": [ "Cooking" ] },
{ "name": "チカラ薬", "en": "Mighty Elixir", "types": [ "Cooking" ] }
], [
{ "name": "祠 6基攻略", "en": "6 Shrines", "types": [ "Shrine" ] },
{ "name": "コログのミ 10個", "en": "10 Koroks", "types": [ "Plateau Korok", "Central Hyrule Korok", "Hateno Korok", "Faron Korok", "Ridgeland Korok", "Lake Korok", "Wasteland Korok", "Woodland Korok", "Lanayru Korok", "Eldin Korok", "Akkala Korok", "Tabantha Korok", "Gerudo Korok", "Hebra Korok", "Dueling Peaks Korok" ] },
{ "name": "始まりの塔エリア コログのミ 5個", "en": "5 Great Plateau Koroks", "types": [ "Plateau Korok", "Plateau" ] },
{ "name": "平原の塔エリア コログのミ 3個", "en": "3 Central Tower Koroks", "types": [ "Central Hyrule Korok", "Central Hyrule" ] },
{ "name": "湖の塔エリア コログのミ 3個", "en": "3 Lake Tower Koroks", "types": [ "Lake Korok", "Lake" ] },
{ "name": "ほこらチャレンジ:花を踏まないで", "en": "'Watch Out for the Flowers' Shrine Quest", "types": [ "Shrine", "Shrine Quest", "Dueling Peaks" ] },
{ "name": "“モリブリン”系武器入手", "en": "Any 'Moblin' Equipment item", "types": [ "Equipment" ] },
{ "name": "馬を登録する", "en": "Register a Horse", "types": [ "Horse" ] },
{ "name": "テリーにカブトムシをあげる", "en": "Give Beedle a Beetle", "types": [ "Horse" ] },
{ "name": "ピリ辛薬", "en": "Spicy Elixir", "types": [ "Cooking" ] },
{ "name": "木のオタマ", "en": "Soup Ladle", "types": [ "Equipment" ] },
{ "name": "“森人の”武器入手", "en": "Any 'Forest Dweller's' Equipment item", "types": [ "Equipment" ] },
{ "name": "“○○の骨”入手", "en": "Any Stalfos 'Arm' Equipment item", "types": [ "Equipment" ] },
{ "name": "ミニチャレンジ 3個攻略", "en": "3 Side Quests", "types": [ "Side Quest" ] },
{ "name": "燃えず薬", "en": "Fireproof Elixir", "types": [ "Cooking" ] },
{ "name": "双子山の塔を起動", "en": "Activate Dueling Peaks Tower", "types": [ "Tower", "Dueling Peaks" ] }
], [
{ "name": "大妖精1人解放", "en": "Pay 1 Great Fairy", "types": [ "Rupee", "Great Fairy" ] },
{ "name": "双子山の塔エリア コログのミ 3個", "en": "3 Dueling Peaks Koroks", "types": [ "Dueling Peaks Korok", "Dueling Peaks" ] },
{ "name": "丘陵の塔エリア コログのミ 3個", "en": "3 Ridgeland Koroks", "types": [ "Ridgeland Korok", "Ridgeland" ] },
{ "name": "荒野の塔エリア コログのミ 3個", "en": "3 Wasteland Koroks", "types": [ "Wasteland Korok", "Wasteland" ] },
{ "name": "ハイリアのフード", "en": "Hylian Hood", "types": [ "Clothes", "Hylian Gear", "Rupee" ] },
{ "name": "ハイリアの服", "en": "Hylian Tunic", "types": [ "Clothes", "Hylian Gear", "Rupee", "Rupee" ] },
{ "name": "ハイリア兵の兜", "en": "Soldier's Helm", "types": [ "Clothes", "Soldier Gear", "Rupee", "Hateno" ] },
{ "name": "ハイリア兵の鎧", "en": "Soldier's Armor", "types": [ "Clothes", "Soldier Gear", "Rupee", "Hateno" ] },
{ "name": "ハイリア兵のすねあて", "en": "Soldier's Greaves", "types": [ "Clothes", "Soldier Gear", "Rupee", "Hateno" ] },
{ "name": "ミニチャレンジ:ココナ's キッチン", "en": "1 Koko Cooking Side Quest", "types": [ "Side Quest", "Dueling Peaks" ] },
{ "name": "ミニチャレンジ:燃える矢じりで貫いて！", "en": "'Arrows of Burning Heat' Side Quest", "types": [ "Side Quest", "Dueling Peaks" ] },
{ "name": "力の試練 序位 ", "en": "A Minor Test of Strength Shrine", "types": [ "Shrine", "Guardian" ] },
{ "name": "畑のクワ", "en": "Farming Hoe", "types": [ "Equipment" ] },
{ "name": "ガッツ系料理", "en": "Any Enduring meal", "types": [ "Cooking", "Stamina" ] },
{ "name": "チカラ系料理", "en": "Any Mighty meal", "types": [ "Cooking" ] },
{ "name": "マックス系料理", "en": "Any Hearty meal", "types": [ "Cooking" ] },
{ "name": "カチコチ系料理", "en": "Any Tough meal", "types": [ "Cooking" ] },
{ "name": "マックス薬", "en": "Hearty Elixir", "types": [ "Cooking" ] },
{ "name": "がんばり薬", "en": "Energizing Elixir", "types": [ "Cooking" ] },
{ "name": "ガッツ薬", "en": "Enduring Elixir", "types": [ "Cooking" ] },
{ "name": "しのび薬", "en": "Sneaky Elixir", "types": [ "Cooking" ] },
{ "name": "イワロック討伐 (どの種でも可)", "en": "Kill a Stone Talus of any kind", "types": [ "Rupee", "Gems", "Miniboss", "Talus" ] },
{ "name": "イワロック(ノーマル)討伐", "en": "Kill a (normal) Stone Talus", "types": [ "Rupee", "Gems", "Miniboss", "Talus" ] },
{ "name": "朽ちたガーディアン討伐", "en": "Kill a Decayed Guardian", "types": [ "Miniboss", "Guardian" ] },
{ "name": "炎属性武器", "en": "Any Fire-typed Equipment item", "types": [ "Equipment" ] },
{ "name": "ミニチャレンジ:プリコと遊ぼ！", "en": "'Playtime with Cottla' Side Quest", "types": [ "Side Quest", "Dueling Peaks" ] },
{ "name": "ミニチャレンジ:水底に沈むお宝", "en": "'Riverbed Reward' Side Quest", "types": [ "Side Quest", "Central Hyrule" ] },
{ "name": "ほこらチャレンジ:二つの輪", "en": "'The Two Rings' Shrine Quest", "types": [ "Shrine", "Shrine Quest", "Ridgeland" ] },
{ "name": "パーヤの日記を読む", "en": "Read Paya's Diary", "types": [ "Dueling Peaks" ] },
{ "name": "“ゾーラの”武器入手", "en": "Any 'Zora' Equipment item", "types": [ "Equipment" ] },
{ "name": "木のモップ", "en": "Wooden Mop", "types": [ "Equipment" ] },
{ "name": "コッコを怒らせる", "en": "Anger a Cucco", "types": [ "Cucco" ] },
{ "name": "ミニチャレンジ 4個攻略", "en": "4 Side Quests", "types": [ "Side Quest" ] },
{ "name": "平原の塔を起動", "en": "Activate Central Tower", "types": [ "Tower", "Central Hyrule" ] }
], [
{ "name": "コログのミ 15個", "en": "15 Koroks", "types": [ "Plateau Korok", "Central Hyrule Korok", "Hateno Korok", "Faron Korok", "Ridgeland Korok", "Lake Korok", "Wasteland Korok", "Woodland Korok", "Lanayru Korok", "Eldin Korok", "Akkala Korok", "Tabantha Korok", "Gerudo Korok", "Hebra Korok", "Dueling Peaks Korok" ] },
{ "name": "ハテノ塔エリア コログのミ 3個", "en": "3 Hateno Koroks", "types": [ "Hateno Korok", "Hateno" ] },
{ "name": "フィローネの塔エリア コログのミ 3個", "en": "3 Faron Koroks", "types": [ "Faron Korok", "Faron" ] },
{ "name": "双子山の塔エリア コログのミ 6個", "en": "6 Dueling Peaks Koroks", "types": [ "Dueling Peaks Korok", "Dueling Peaks" ] },
{ "name": "ラネールの塔エリア コログのミ 3個", "en": "3 Lanayru Koroks", "types": [ "Lanayru Korok", "Lanayru" ] },
{ "name": "タバンタの塔エリア コログのミ 3個", "en": "3 Tabantha Koroks", "types": [ "Tabantha Korok", "Tabantha" ] },
{ "name": "湖の塔エリア コログのミ 6個", "en": "6 Lake Tower Koroks", "types": [ "Lake Korok", "Lake" ] },
{ "name": "荒野の塔エリア コログのミ 6個", "en": "6 Wasteland Koroks", "types": [ "Wasteland Korok", "Wasteland" ] },
{ "name": "丘陵の塔エリア コログのミ 6個", "en": "6 Ridgeland Koroks", "types": [ "Ridgeland Korok", "Ridgeland" ] },
{ "name": "平原の塔エリア コログのミ 6個", "en": "6 Central Tower Koroks", "types": [ "Central Hyrule Korok", "Central Hyrule" ] },
{ "name": "ミニチャレンジ:その馬買い取ります！", "en": "'A Good-Sized Horse' Side Quest", "types": [ "Side Quest", "Wasteland", "Horse" ] },
{ "name": "ミニチャレンジ:大事なマラカス", "en": "'The Priceless Maracas' Side Quest", "types": [ "Side Quest", "Dueling Peaks" ] },
{ "name": "ほこらチャレンジ:ガマンくらべ", "en": "'Test of Will' Shrine Quest", "types": [ "Shrine", "Shrine Quest", "Gerudo" ] },
{ "name": "ミニチャレンジ:野生馬を捕まえて", "en": "'Wild Horses' Side Quest", "types": [ "Side Quest", "Dueling Peaks", "Horse" ] },
{ "name": "ミニチャレンジ:消えたコッコちゃん", "en": "'Flown the Coop' Side Quest", "types": [ "Side Quest", "Dueling Peaks", "Heirloom" ] },
{ "name": "ハイリア防具一式", "en": "Full Hylian Set", "types": [ "Clothes", "Hylian Gear", "Rupee" ] },
{ "name": "クライムバンダナ", "en": "Climber's Bandanna", "types": [ "Clothes", "Climbing Gear", "Dueling Peaks" ] },
{ "name": "ウィズローブ討伐", "en": "Kill a Wizzrobe of any kind", "types": [ "Wizzrobe" ] },
{ "name": "忍びマスク", "en": "Stealth Mask", "types": [ "Clothes", "Stealth Gear", "Rupee", "Dueling Peaks" ] },
{ "name": "忍びタイツ", "en": "Stealth Tights", "types": [ "Clothes", "Stealth Gear", "Rupee", "Dueling Peaks" ] },
{ "name": "ブーメラン系武器入手", "en": "Any Boomerang", "types": [ "Equipment" ] },
{ "name": "“リザル”系武器入手", "en": "Any 'Lizal' Equipment item", "types": [ "Equipment" ] },
{ "name": "ヒンヤリ系料理", "en": "Any Chilly meal", "types": [ "Cooking", "Wasteland" ] },
{ "name": "エレキ系料理", "en": "Any Electro meal", "types": [ "Cooking" ] },
{ "name": "ヒンヤリ薬", "en": "Chilly Elixir", "types": [ "Cooking" ] },
{ "name": "氷属性武器", "en": "Any Ice-typed Equipment item", "types": [ "Equipment" ] },
{ "name": "妖精の力水", "en": "Any Fairy Tonic", "types": [ "Cooking" ] },
{ "name": "エレキ薬", "en": "Electro Elixir", "types": [ "Cooking" ] },
{ "name": "炎属性ウィズローブ討伐", "en": "Kill a fire-typed Wizzrobe", "types": [ "Wizzrobe" ] },
{ "name": "氷属性ウィズローブ討伐", "en": "Kill an ice-typed Wizzrobe", "types": [ "Wizzrobe" ] },
{ "name": "湖の塔を起動", "en": "Activate Lake Tower", "types": [ "Tower", "Lake" ] },
{ "name": "ヒノックス討伐 (どの種でも可)", "en": "Kill a Hinox of any kind", "types": [ "Miniboss", "Hinox" ] },
{ "name": "ミニゲーム:鳥人間チャレンジ 500m以上滑空", "en": "500m in the Gliding Minigame", "types": [ "Minigame", "Ridgeland" ] }
], [
{ "name": "森林の塔エリア コログのミ 3個", "en": "3 Woodland Koroks", "types": [ "Woodland Korok", "Woodland" ] },
{ "name": "オルディンの塔エリア コログのミ 3個", "en": "3 Eldin Koroks", "types": [ "Eldin Korok", "Eldin" ] },
{ "name": "ラネールの塔エリア コログのミ 6個", "en": "6 Lanayru Koroks", "types": [ "Lanayru Korok", "Lanayru" ] },
{ "name": "ゲルドの塔エリア コログのミ 3個", "en": "3 Gerudo Koroks", "types": [ "Gerudo Korok", "Gerudo" ] },
{ "name": "ハイリアのフード(赤色)", "en": "Red Dyed Hylian Hood", "types": [ "Clothes", "Hylian Gear", "Hateno" ] },
{ "name": "ハイリアのフード(黄色)", "en": "Yellow Dyed Hylian Hood", "types": [ "Clothes", "Hylian Gear", "Hateno" ] },
{ "name": "ハイリアのフード(紫色)", "en": "Purple Dyed Hylian Hood", "types": [ "Clothes", "Hylian Gear", "Hateno" ] },
{ "name": "ハイリアのフード(緑色)", "en": "Green Dyed Hylian Hood", "types": [ "Clothes", "Hylian Gear", "Hateno" ] },
{ "name": "ハイリアのフード(薄黄色)", "en": "Light Yellow Dyed Hylian Hood", "types": [ "Clothes", "Hylian Gear", "Hateno" ] },
{ "name": "ハイリアのフード(灰色)", "en": "Gray Dyed Hylian Hood", "types": [ "Clothes", "Hylian Gear", "Hateno" ] },
{ "name": "忍びスーツ", "en": "Stealth Chest Guard", "types": [ "Clothes", "Stealth Gear", "Rupee", "Dueling Peaks" ] },
{ "name": "ミニチャレンジ:ココナ's キッチン４", "en": "4 Koko Cooking Side Quests", "types": [ "Side Quest", "Dueling Peaks" ] },
{ "name": "ミニチャレンジ:暑さをしのぐ薬", "en": "'An Ice Guy' Side Quest", "types": [ "Side Quest", "Wasteland" ] },
{ "name": "ミニチャレンジ:王家の白馬", "en": "'The Royal White Stallion' Side Quest", "types": [ "Side Quest", "Central Hyrule", "Horse", "Stamina" ] },
{ "name": "ゼルダの日録を読む", "en": "Read Zelda's Diary", "types": [ "Hyrule Castle" ] },
{ "name": "ガーディアン(歩行型)討伐", "en": "Kill a Guardian Stalker", "types": [ "Miniboss", "Guardian" ] },
{ "name": "プルアの日記を読む", "en": "Read Purah's Diary", "types": [ "Hateno" ] },
{ "name": "ハテノ塔を起動", "en": "Activate Hateno Tower", "types": [ "Tower", "Hateno" ] },
{ "name": "フィローネの塔を起動", "en": "Activate Faron Tower", "types": [ "Tower", "Faron" ] },
{ "name": "丘陵の塔を起動", "en": "Activate Ridgeland Tower", "types": [ "Tower", "Ridgeland" ] }
], [
{ "name": "コログのミ 20個", "en": "20 Koroks", "types": [ "Plateau Korok", "Central Hyrule Korok", "Hateno Korok", "Faron Korok", "Ridgeland Korok", "Lake Korok", "Wasteland Korok", "Woodland Korok", "Lanayru Korok", "Eldin Korok", "Akkala Korok", "Tabantha Korok", "Gerudo Korok", "Hebra Korok", "Dueling Peaks Korok" ] },
{ "name": "アッカレの塔エリア コログのミ 3個", "en": "3 Akkala Koroks", "types": [ "Akkala Korok", "Akkala" ] },
{ "name": "ハイリアのフード(青色)", "en": "Blue Dyed Hylian Hood", "types": [ "Clothes", "Hylian Gear", "Hateno" ] },
{ "name": "ハイリアのフード(白色)", "en": "White Dyed Hylian Hood", "types": [ "Clothes", "Hylian Gear", "Hateno" ] },
{ "name": "ハイリアのフード(薄青色)", "en": "Light Blue Dyed Hylian Hood", "types": [ "Clothes", "Hylian Gear", "Hateno" ] },
{ "name": "ハイリアのフード(橙色)", "en": "Orange Dyed Hylian Hood", "types": [ "Clothes", "Hylian Gear", "Hateno" ] },
{ "name": "ハイリアのフード(深紅色)", "en": "Crimson Dyed Hylian Hood", "types": [ "Clothes", "Hylian Gear", "Hateno" ] },
{ "name": "ハイリアのフード(茶色)", "en": "Brown Dyed Hylian Hood", "types": [ "Clothes", "Hylian Gear", "Hateno" ] },
{ "name": "双子山の塔エリア 祠3基", "en": "3 Dueling Peaks Shrines", "types": [ "Shrine", "Dueling Peaks" ] },
{ "name": "ガーディアン(砲台型)討伐", "en": "Kill a Guardian Turret", "types": [ "Miniboss", "Guardian", "Hyrule Castle" ] },
{ "name": "ライネル討伐", "en": "Kill a Lynel", "types": [ "Miniboss", "Lynel" ] },
{ "name": "ヒノックス(赤)討伐", "en": "Kill a (red) Hinox", "types": [ "Miniboss", "Hinox" ] },
{ "name": "ラネールの塔を起動", "en": "Activate Lanayru Tower", "types": [ "Tower", "Lanayru" ] },
{ "name": "淑女防具一式", "en": "Gerudo Set", "types": [ "Clothes", "Wasteland", "Rupee" ] },
{ "name": "イワロック(希少)討伐", "en": "Kill a Stone Talus (Rare)", "types": [ "Rupee", "Miniboss", "Talus" ] },
{ "name": "オルドラの素材を入手", "en": "Obtain a Material from Dinraal", "types": [ "Dragon" ] },
{ "name": "ネルドラの素材を入手", "en": "Obtain a Material from Naydra", "types": [ "Hateno", "Cold Resistance", "Dragon" ] },
{ "name": "ミニチャレンジ:器の操者", "en": "'The Statue's Bargain' Side Quest", "types": [ "Side Quest", "Hateno" ] },
{ "name": "ガーディアン(飛行型)討伐", "en": "Kill a Guardian Skywatcher", "types": [ "Miniboss", "Guardian" ] },
{ "name": "ハイラル王の手記を読む", "en": "Read King's Diary", "types": [ "Hyrule Castle" ] },
{ "name": "雷属性ウィズローブ討伐", "en": "Kill an electric-typed Wizzrobe", "types": [ "Wizzrobe" ] },
{ "name": "ハートの器 計5個", "en": "5 Heart Containers", "types": [ "Shrine", "Heart" ] },
{ "name": "がんばりの器 2つ入手", "en": "2 Stamina Vessels", "types": [ "Shrine", "Stamina" ] },
{ "name": "ロベリーの日記を読む", "en": "Read Robbie's Diary", "types": [ "Akkala" ] },
{ "name": "荒野の塔を起動", "en": "Activate Wasteland Tower", "types": [ "Tower", "Wasteland" ] }
], [
{ "name": "森林の塔エリア コログのミ 6個", "en": "6 Woodland Koroks", "types": [ "Woodland Korok", "Woodland" ] },
{ "name": "ハテノ塔エリア コログのミ 6個", "en": "6 Hateno Koroks", "types": [ "Hateno Korok", "Hateno" ] },
{ "name": "フィローネの塔エリア コログのミ 6個", "en": "6 Faron Koroks", "types": [ "Faron Korok", "Faron" ] },
{ "name": "ハイリアの服シリーズ★", "en": "any Hylian Series ★", "types": [ "Clothes", "Hylian Gear", "Rupee", "Great Fairy" ] },
{ "name": "ハイリアの盾", "en": "Hylian Shield", "types": [ "Miniboss", "Hinox", "Hyrule Castle" ] },
{ "name": "ハイリア兵防具一式", "en": "Full Soldier's Set", "types": [ "Clothes", "Soldier Gear", "Rupee", "Hateno" ] },
{ "name": "ゾーラの兜", "en": "Zora Helm", "types": [ "Clothes", "Zora Gear", "Lanayru" ] },
{ "name": "ゾーラの鎧", "en": "Zora Armor", "types": [ "Clothes", "Zora Gear", "Lanayru" ] },
{ "name": "ハイリアのフード(黒色)", "en": "Black Dyed Hylian Hood", "types": [ "Clothes", "Hylian Gear", "Hateno" ] },
{ "name": "ハイリアのフード(紺色)", "en": "Navy Dyed Hylian Hood", "types": [ "Clothes", "Hylian Gear", "Hateno" ] },
{ "name": "ハイリアのフード(桃色)", "en": "Peach Dyed Hylian Hood", "types": [ "Clothes", "Hylian Gear", "Hateno" ] },
{ "name": "ミニチャレンジ:勇者の蓄え？", "en": "'The Hero's Cache' Side Quest", "types": [ "Side Quest", "Hateno" ] },
{ "name": "ミニチャレンジ:雷怖い", "en": "'Thunder Magnet' Side Quest", "types": [ "Side Quest", "Faron", "Rubber Gear" ] },
{ "name": "ミニチャレンジ:飛び込みに目覚めた男", "en": "'Diving is Beauty!' Side Quest", "types": [ "Side Quest", "Lanayru" ] },
{ "name": "ミニチャレンジ:ハイラル城に眠る武器", "en": "'The Royal Guard's Gear' Side Quest", "types": [ "Side Quest", "Hyrule Castle" ] },
{ "name": "ミニチャレンジ:馬に乗った荒くれ者", "en": "'The Horseback Hoodlums' Side Quest", "types": [ "Side Quest", "Lake" ] },
{ "name": "ほこらチャレンジ:呪われし石像", "en": "'The Cursed Statue' Shrine Quest", "types": [ "Shrine", "Shrine Quest", "Hateno" ] },
{ "name": "ほこらチャレンジ:二本槍の獣", "en": "'Crowned Beast' Shrine Quest", "types": [ "Shrine", "Shrine Quest", "Hateno", "Horse" ] },
{ "name": "湖の塔エリア 祠3基", "en": "3 Lake Shrines", "types": [ "Shrine", "Lake" ] },
{ "name": "平原の塔エリア 祠3基", "en": "3 Central Tower Shrines", "types": [ "Shrine", "Central Hyrule" ] },
{ "name": "青ヒノックス討伐", "en": "Kill a Blue Hinox", "types": [ "Miniboss", "Hinox" ] },
{ "name": "スタルヒノックス討伐", "en": "Kill a Stalnox", "types": [ "Miniboss", "Hinox" ] },
{ "name": "雷属性武器", "en": "Any Electric-typed Equipment item", "types": [ "Equipment" ] },
{ "name": "上位ロッド入手", "en": "Any second tier Rod weapon", "types": [ "Equipment", "Wizzrobe" ] },
{ "name": "ヘブラの塔を起動", "en": "Activate Hebra Tower", "types": [ "Tower", "Hebra", "Cold Resistance" ] }
], [
{ "name": "祠 8基攻略", "en": "8 Shrines", "types": [ "Shrine" ] },
{ "name": "ヘブラの塔エリア コログのミ 3個", "en": "3 Hebra Koroks", "types": [ "Hebra Korok", "Hebra", "Cold Resistance" ] },
{ "name": "コログのミ 20個", "en": "20 Koroks", "types": [ "Plateau Korok", "Central Hyrule Korok", "Hateno Korok", "Faron Korok", "Ridgeland Korok", "Lake Korok", "Wasteland Korok", "Woodland Korok", "Lanayru Korok", "Eldin Korok", "Akkala Korok", "Tabantha Korok", "Gerudo Korok", "Hebra Korok", "Dueling Peaks Korok" ] },
{ "name": "クライムシューズ", "en": "Climbing Boots", "types": [ "Clothes", "Climbing Gear", "Hateno" ] },
{ "name": "船のオール", "en": "Boat Oar", "types": [ "Equipment" ] },
{ "name": "ミニチャレンジ:秘密クラブの秘密", "en": "'The Secret Club's Secret' Side Quest", "types": [ "Side Quest", "Wasteland", "Radiant Gear", "Desert Gear" ] },
{ "name": "丘陵の塔エリア 祠3基", "en": "3 Ridgeland Shrines", "types": [ "Shrine", "Ridgeland" ] },
{ "name": "黒ヒノックス討伐", "en": "Kill a Black Hinox", "types": [ "Miniboss", "Hinox" ] },
{ "name": "ミニチャレンジ:こおりの杖しれん", "en": "'A Freezing Rod' Side Quest", "types": [ "Side Quest", "Woodland", "Wizzrobe" ] },
{ "name": "ほこらチャレンジ:燃えずのしれん", "en": "'The Test of Wood' Shrine Quest", "types": [ "Shrine", "Shrine Quest", "Woodland" ] },
{ "name": "ほこらチャレンジ:操りの力のしれん", "en": "'Trial of Second Sight' Shrine Quest", "types": [ "Shrine", "Shrine Quest", "Woodland" ] },
{ "name": "ほこらチャレンジ:馬宿の風景画", "en": "'A Landscape of a Stable' Shrine Quest", "types": [ "Shrine", "Shrine Quest", "Eldin" ] },
{ "name": "フロドラの素材を入手", "en": "Obtain a Material from Farosh", "types": [ "Dragon" ] },
{ "name": "ミニゲーム:鹿狩り 鹿を5頭狩る", "en": "5 Deer in Hunting Minigame", "types": [ "Minigame", "Hateno" ] }
], [
{ "name": "タバンタの塔エリア コログのミ 6個", "en": "6 Tabantha Koroks", "types": [ "Tabantha Korok", "Tabantha" ] },
{ "name": "双子山の塔エリア コログのミ 9個", "en": "9 Dueling Peaks Koroks", "types": [ "Dueling Peaks Korok", "Dueling Peaks" ] },
{ "name": "平原の塔エリア コログのミ 9個", "en": "9 Central Tower Koroks", "types": [ "Central Hyrule Korok", "Central Hyrule" ] },
{ "name": "クライムバンダナ★", "en": "Climber's Bandanna ★", "types": [ "Clothes", "Climbing Gear", "Great Fairy" ] },
{ "name": "リトの羽毛服", "en": "Snowquill Tunic", "types": [ "Clothes", "Snow Gear", "Cold Resistance", "Rupee", "Tabantha" ] },
{ "name": "リトの羽毛ズボン", "en": "Snowquill Trousers", "types": [ "Clothes", "Snow Gear", "Cold Resistance", "Rupee", "Tabantha" ] },
{ "name": "クライムグローブ", "en": "Climbing Gear", "types": [ "Clothes", "Climbing Gear", "Hateno" ] },
{ "name": "ミニチャレンジ:新妻は花よりダンゴ", "en": "'The Apple of My Eye' Side Quest", "types": [ "Side Quest", "Tabantha" ] },
{ "name": "忘れられた神殿の祠", "en": "Forgotten Temple Shrine", "types": [ "Shrine", "Shrine Quest", "Woodland" ] },
{ "name": "ミニチャレンジ:大盗賊ラムダの秘宝", "en": "'Misko, the Great Bandit' Side Quest", "types": [ "Side Quest", "Dueling Peaks" ] },
{ "name": "ミニチャレンジ:大妖精さまのおふせ", "en": "'A Gift for the Great Fairy' Side Quest", "types": [ "Side Quest", "Tabantha", "Rupee", "Great Fairy" ] },
{ "name": "ミニチャレンジ:今日の晩御飯", "en": "'What's for Dinner?' Side Quest", "types": [ "Side Quest", "Faron" ] },
{ "name": "ミニチャレンジ:巨大馬捕獲大作戦", "en": "'Hunt for the Giant Horse' Side Quest", "types": [ "Side Quest", "Lake", "Horse", "Stamina" ] },
{ "name": "荒野の塔エリア 祠3基", "en": "3 Wasteland Shrines", "types": [ "Shrine", "Wasteland" ] },
{ "name": "“双子の記憶”の両祠", "en": "'Twin Memories' Shrines", "types": [ "Shrine", "Shrine Quest", "Dueling Peaks" ] },
{ "name": "力の試練 中位のガーディアンを倒す", "en": "A Modest Test of Strength Shrine of Killing the Guardian", "types": [ "Shrine", "Guardian" ] },
{ "name": "ガーディアンアクス (+付きも可)", "en": "Any Ancient Battle Axe", "types": [ "Equipment", "Guardian" ] },
{ "name": "ほこらチャレンジ:三本杉の秘密", "en": "'Secret of the Cedars' Shrine Quest", "types": [ "Shrine", "Shrine Quest", "Hateno" ] },
{ "name": "ほこらチャレンジ:消える？砂嵐", "en": "'The Eye of the Sandstorm' Shrine Quest", "types": [ "Shrine", "Shrine Quest", "Wastelands" ] },
{ "name": "ガーディアンシールド (+付きも可)", "en": "Any Guardian Shield", "types": [ "Equipment", "Guardian" ] },
{ "name": "ミニゲーム:ガンガンゴルフをクリア", "en": "Finish Golf Minigame", "types": [ "Minigame", "Woodland" ] },
{ "name": "ミニゲーム:雪玉ボウルで遊ぶ", "en": "Play the Bowling Minigame", "types": [ "Minigame", "Hebra", "Cold Resistance" ] },
{ "name": "タバンタの塔を起動", "en": "Activate Tabantha Tower", "types": [ "Tower", "Tabantha" ] },
{ "name": "森林の塔を起動", "en": "Activate Woodland Tower", "types": [ "Tower", "Woodland" ] }
], [
{ "name": "闘技場のライネル討伐", "en": "Kill Coliseum Lynel", "types": [ "Miniboss", "Lynel", "Central Hyrule" ] },
{ "name": "ラバーキャップ★", "en": "Rubber Helm ★", "types": [ "Clothes", "Rubber Gear", "Faron", "Great Fairy" ] },
{ "name": "忍び防具一式", "en": "Full Stealth Set", "types": [ "Clothes", "Stealth Gear", "Rupee", "Dueling Peaks" ] },
{ "name": "雪よけの羽飾り", "en": "Snowquill Headdress", "types": [ "Clothes", "Snow Gear", "Cold Resistance", "Rupee", "Tabantha" ] },
{ "name": "3属性の武器を1つずつ入手", "en": "1 Fire, 1 Ice, and 1 Electric weapons", "types": [ "Equipment" ] },
{ "name": "ほこらチャレンジ:風を束ねて制する者よ", "en": "'Master of the Wind' Shrine Quest", "types": [ "Shrine", "Shrine Quest", "Lanayru" ] },
{ "name": "ミニチャレンジ:愛しの人が望む物", "en": "'A Gift for My Beloved' Side Quest", "types": [ "Side Quest", "Hateno" ] },
{ "name": "ミニチャレンジ:海に沈んだ財宝", "en": "'Sunken Treasure' Side Quest", "types": [ "Side Quest", "Hateno" ] },
{ "name": "ミニチャレンジ:新郎の汚名返上", "en": "'The Spark of Romance' Side Quest", "types": [ "Side Quest", "Tabantha" ] },
{ "name": "ミニチャレンジ:風船よ舞い上がれ！", "en": "'Balloon Flight' Side Quest", "types": [ "Side Quest", "Woodland" ] },
{ "name": "ほこらチャレンジ:雪山の日誌", "en": "'Secret of the Snowy Peaks' Shrine Quest", "types": [ "Shrine", "Shrine Quest", "Wastelands", "Cold Resistance" ] },
{ "name": "ほこらチャレンジ:稲妻が開く試練", "en": "'Song of Storms' Shrine Quest", "types": [ "Shrine", "Shrine Quest", "Faron" ] },
{ "name": "ほこらチャレンジ:砂漠の試練", "en": "'The Desert Labyrinth' Shrine Quest", "types": [ "Shrine", "Shrine Quest", "Wastelands", "Barbarian Gear" ] },
{ "name": "ほこらチャレンジ:はじめてのしれん", "en": "'The Lost Pilgrimage' Shrine Quest", "types": [ "Shrine", "Shrine Quest", "Woodland" ] },
{ "name": "ラネールの塔エリア 祠3基", "en": "3 Lanayru Shrines", "types": [ "Shrine", "Lanayru" ] },
{ "name": "熊に乗る", "en": "Mount a Bear", "types": [ "Horse", "Stamina" ] },
{ "name": "フルーツケーキ", "en": "Fruitcake", "types": [ "Cooking" ] },
{ "name": "スタルホースに乗る", "en": "Mount a Stalhorse", "types": [ "Horse" ] },
{ "name": "馬神マーロン解放", "en": "Pay Horse God Malanya", "types": [ "Lake", "Rupee" ] },
{ "name": "アッカレの塔を起動", "en": "Activate Akkala Tower", "types": [ "Tower", "Akkala" ] }
], [
{ "name": "コログのミ 25個", "en": "25 Koroks", "types": [ "Plateau Korok", "Central Hyrule Korok", "Hateno Korok", "Faron Korok", "Ridgeland Korok", "Lake Korok", "Wasteland Korok", "Woodland Korok", "Lanayru Korok", "Eldin Korok", "Akkala Korok", "Tabantha Korok", "Gerudo Korok", "Hebra Korok", "Dueling Peaks Korok" ] },
{ "name": "アッカレの塔エリア コログのミ 6個", "en": "6 Akkala Koroks", "types": [ "Akkala Korok", "Akkala" ] },
{ "name": "オルディンの塔エリア コログのミ 6個", "en": "6 Eldin Koroks", "types": [ "Eldin Korok", "Eldin" ] },
{ "name": "湖の塔エリア コログのミ 9個", "en": "9 Lake Tower Koroks", "types": [ "Lake Korok", "Lake" ] },
{ "name": "タバンタの塔エリア コログのミ 9個", "en": "9 Tabantha Koroks", "types": [ "Tabantha Korok", "Tabantha" ] },
{ "name": "森林の塔エリア コログのミ 9個", "en": "9 Woodland Koroks", "types": [ "Woodland Korok", "Woodland" ] },
{ "name": "オルディンの塔エリア 祠3基", "en": "3 Eldin Shrines", "types": [ "Shrine", "Eldin" ] },
{ "name": "フィローネの塔エリア 祠3基", "en": "3 Faron Shrines", "types": [ "Shrine", "Faron" ] },
{ "name": "タバンタの塔エリア 祠3基", "en": "3 Tabantha Shrines", "types": [ "Shrine", "Tabantha" ] },
{ "name": "森林の塔エリア 祠3基", "en": "3 Woodland Shrines", "types": [ "Shrine", "Woodland" ] },
{ "name": "英傑の服", "en": "Champion's Tunic", "types": [ "Clothes", "Champion", "Camera" ] },
{ "name": "耐火の石鎧", "en": "Flamebreaker Armor", "types": [ "Clothes", "Flame Gear", "Eldin", "Rupee" ] },
{ "name": "耐火の石靴", "en": "Flamebreaker Boots", "types": [ "Clothes", "Flame Gear", "Eldin", "Rupee" ] },
{ "name": "任意のハイリア兵シリーズ★", "en": "any Soldier's Series ★", "types": [ "Clothes", "Soldier Gear", "Rupee", "Great Fairy" ] },
{ "name": "任意の忍びシリーズ★", "en": "any Stealth Series ★", "types": [ "Clothes", "Stealth Gear", "Rupee", "Great Fairy" ] },
{ "name": "ラバースーツ★", "en": "Rubber Armor ★", "types": [ "Clothes", "Rubber Gear", "Ridgeland", "Great Fairy" ] },
{ "name": "ラバータイツ★", "en": "Rubber Tights ★", "types": [ "Clothes", "Rubber Gear", "Faron", "Great Fairy" ] },
{ "name": "スノーブーツ", "en": "Snow Boots", "types": [ "Clothes", "Boots", "Side Quest", "Gerudo", "Camera" ] },
{ "name": "ハテノ塔エリア 祠3基", "en": "3 Hateno Shrines", "types": [ "Shrine", "Hateno" ] },
{ "name": "ほこらチャレンジ 2つ攻略", "en": "2 Shrine Quests", "types": [ "Shrine", "Shrine Quest" ] },
{ "name": "ほこらチャレンジ:暗闇の試練", "en": "'Shrouded Shrine' Shrine Quest", "types": [ "Shrine", "Shrine Quest", "Woodland" ] },
{ "name": "ほこらチャレンジ:口を閉ざした戦士", "en": "'The Silent Swordswomen' Shrine Quest", "types": [ "Shrine", "Shrine Quest", "Wastelands" ] },
{ "name": "ほこらチャレンジ:絶壁の文様", "en": "'Cliffside Etchings' Shrine Quest", "types": [ "Shrine", "Shrine Quest", "Gerudo", "Cold Resistance" ] },
{ "name": "ほこらチャレンジ:影が示す先に", "en": "'Sign of the Shadow' Shrine Quest", "types": [ "Shrine", "Shrine Quest", "Gerudo" ] },
{ "name": "ウツシエの記憶 1つ回収", "en": "Collect 1 Picture Memory", "types": [ "Camera" ] },
{ "name": "大妖精 2人解放", "en": "Pay 2 Great Fairies", "types": [ "Rupee", "Great Fairy" ] },
{ "name": "マモノケーキ", "en": "Monster cake", "types": [ "Cooking", "Kilton" ] },
{ "name": "カッシーワとツーショット", "en": "Take a Selfie with Kass", "types": [ "Camera" ] },
{ "name": "ミニチャレンジ:にっくきヒツジ泥棒", "en": "'The Sheep Rustlers' Side Quest", "types": [ "Side Quest", "Hateno" ] },
{ "name": "ミニチャレンジ:ゲルドキャニオン失踪事件", "en": "'Missing in Action' Side Quest", "types": [ "Side Quest", "Wasteland" ] },
{ "name": "ミニチャレンジ:ウツシエとシーカーセンサー", "en": "'Sunshroom Sensing' Side Quest", "types": [ "Side Quest", "Hateno", "Camera" ] },
{ "name": "ゲルドの塔を起動", "en": "Activate Gerudo Tower", "types": [ "Tower", "Gerudo" ] }
], [
{ "name": "蛮族の腰巻き", "en": "Barbarian Leg Wraps", "types": [ "Clothes", "Barbarian Gear", "Hebra" ] },
{ "name": "熱砂の鉢がね", "en": "Desert Voe Headband", "types": [ "Clothes", "Desert Gear", "Wasteland", "Rupee" ] },
{ "name": "熱砂のズボン", "en": "Desert Voe Trousers", "types": [ "Clothes", "Desert Gear", "Wasteland", "Rupee" ] },
{ "name": "リトの羽毛服★", "en": "Snowquill Tunic ★", "types": [ "Clothes", "Snow Gear", "Cold Resistance", "Rupee", "Great Fairy" ] },
{ "name": "リトの羽毛ズボン★", "en": "Snowquill Trousers ★", "types": [ "Clothes", "Snow Gear", "Cold Resistance", "Rupee", "Great Fairy" ] },
{ "name": "ハテノ塔エリア コログのミ 9個", "en": "9 Hateno Koroks", "types": [ "Hateno Korok", "Hateno" ] },
{ "name": "ゲルドの塔エリア コログのミ 6個", "en": "6 Gerudo Koroks", "types": [ "Gerudo Korok", "Gerudo" ] },
{ "name": "丘陵の塔エリア コログのミ 9個", "en": "9 Ridgeland Koroks", "types": [ "Ridgeland Korok", "Ridgeland" ] },
{ "name": "ラネールの塔エリア コログのミ 9個", "en": "9 Lanayru Koroks", "types": [ "Lanayru Korok", "Lanayru" ] },
{ "name": "荒野の塔エリア コログのミ 9個", "en": "9 Wasteland Koroks", "types": [ "Wasteland Korok", "Wasteland" ] },
{ "name": "ミニチャレンジ:王家秘伝のレシピ", "en": "'A Royal Recipe' Side Quest", "types": [ "Side Quest", "Central Hyrule", "Cooking" ] },
{ "name": "ほこらチャレンジ:大蛇喰らいし龍", "en": "'The Serpent's Jaws' Shrine Quest", "types": [ "Shrine", "Shrine Quest", "Lake", "Dragon" ] },
{ "name": "ほこらチャレンジ:石碑のかけら探し", "en": "'Fragmented Monument' Shrine Quest", "types": [ "Shrine", "Shrine Quest", "Faron", "Camera" ] }
], [
{ "name": "ヘブラの塔エリア コログのミ 6個", "en": "6 Hebra Koroks", "types": [ "Hebra Korok", "Hebra", "Cold Resistance" ] },
{ "name": "フィローネの塔エリア コログのミ 9個", "en": "9 Faron Koroks", "types": [ "Faron Korok", "Faron" ] },
{ "name": "双子山の塔エリア コログのミ 12個", "en": "12 Dueling Peaks Koroks", "types": [ "Dueling Peaks Korok", "Dueling Peaks" ] },
{ "name": "オルディンの塔エリア コログのミ 9個", "en": "9 Eldin Koroks", "types": [ "Eldin Korok", "Eldin" ] },
{ "name": "平原の塔エリア コログのミ 12個", "en": "12 Central Tower Koroks", "types": [ "Central Hyrule Korok", "Central Hyrule" ] },
{ "name": "ゾーラの兜★", "en": "Zora Helm ★", "types": [ "Clothes", "Zora Gear", "Great Fairy", "Lizalfos" ] },
{ "name": "熱砂の肩当て", "en": "Desert Voe Spaulder", "types": [ "Clothes", "Desert Gear", "Wasteland", "Rupee" ] },
{ "name": "ゾーラの鎧★", "en": "Zora Armor ★", "types": [ "Clothes", "Zora Gear", "Great Fairy", "Lizalfos" ] },
{ "name": "雪よけの羽飾り★", "en": "Snowquill Headdress ★", "types": [ "Clothes", "Snow Gear", "Cold Resistance", "Rupee", "Great Fairy" ] },
{ "name": "カレーピラフ", "en": "Curry Pilaf", "types": [ "Cooking" ] },
{ "name": "任意の夜光シリーズ入手", "en": "any Radiant Series", "types": [ "Clothes", "Radiant Gear", "Rupee", "Gems", "Wasteland" ] },
{ "name": "ヘブラの塔エリア 祠3基", "en": "3 Hebra Shrines", "types": [ "Shrine", "Hebra", "Cold Resistance" ] },
{ "name": "メインチャレンジ:風の神獣ヴァ・メドー", "en": "'Divine Beast Vah Medoh' Main Quest", "types": [ "Divine Beast", "Tabantha", "Cold Resistance" ] },
{ "name": "ミニチャレンジ:奪われた漁場", "en": "'Take Back the Sea' Side Quest", "types": [ "Side Quest", "Faron" ] },
{ "name": "ミニチャレンジ:しのび草の君", "en": "'A Gift of Nightshade' Side Quest", "types": [ "Side Quest", "Faron" ] },
{ "name": "ミニチャレンジ:ヒケシトカゲを捕まえて！", "en": "'Fireproof Lizard Roundup' Side Quest", "types": [ "Side Quest", "Eldin", "Flame Gear" ] },
{ "name": "ミニチャレンジ:寒い時にはカレーを！", "en": "'Curry for What Ails You' Side Quest", "types": [ "Side Quest", "Tabantha", "Eldin" ] },
{ "name": "ミニゲーム:盾サーフィン 初級をクリア", "en": "Finish Basic Shield Surfing Minigame", "types": [ "Minigame", "Hebra", "Cold Resistance" ] },
{ "name": "ゲルドの塔エリア 祠3基", "en": "3 Gerudo Shrines", "types": [ "Shrine", "Gerudo", "Cold Resistance" ] },
{ "name": "ほこらチャレンジ:七人の英雄", "en": "'The Seven Heroines' Shrine Quest", "types": [ "Shrine", "Shrine Quest", "Wastelands" ] },
{ "name": "ミニチャレンジ:ホタル ノ ヒカリ", "en": "'By Firefly's Light' Side Quest", "types": [ "Side Quest", "Dueling Peaks", "Heirloom", "Camera" ] },
{ "name": "ほこらチャレンジ:おっきなお山のおっきな木", "en": "'The Bird in the Mountains' Shrine Quest", "types": [ "Shrine", "Shrine Quest", "Hebra", "Cold Resistance" ] },
{ "name": "ハート 計6個", "en": "6 Heart Containers", "types": [ "Shrine", "Heart" ] },
{ "name": "リモコン爆弾+", "en": "Remote Bomb +", "types": [ "Camera", "Rune Upgrade", "Hateno" ] },
{ "name": "シーカータワー 4基起動", "en": "Activate 4 Towers", "types": [ "Tower" ] },
{ "name": "ミニチャレンジ 11個攻略", "en": "11 Side Quests", "types": [ "Side Quest" ] },
{ "name": "オルディンの塔を起動", "en": "Activate Eldin Tower", "types": [ "Tower", "Eldin" ] }
], [
{ "name": "祠 10基攻略", "en": "10 Shrines", "types": [ "Shrine" ] },
{ "name": "アッカレの塔エリア コログのミ 9個", "en": "9 Akkala Koroks", "types": [ "Akkala Korok", "Akkala" ] },
{ "name": "荒野の塔エリア コログのミ 12個", "en": "12 Wasteland Koroks", "types": [ "Wasteland Korok", "Wasteland" ] },
{ "name": "ハテノ塔エリア コログのミ 12個", "en": "12 Hateno Koroks", "types": [ "Hateno Korok", "Hateno" ] },
{ "name": "湖の塔エリア コログのミ 12個", "en": "12 Lake Tower Koroks", "types": [ "Lake Korok", "Lake" ] },
{ "name": "丘陵の塔エリア コログのミ 12個", "en": "12 Ridgeland Koroks", "types": [ "Ridgeland Korok", "Ridgeland" ] },
{ "name": "クライムシューズ★", "en": "Climbing Boots ★", "types": [ "Clothes", "Climbing Gear", "Great Fairy" ] },
{ "name": "ガチロック討伐", "en": "Kill a Frost Talus", "types": [ "Rupee", "Gems", "Miniboss", "Talus", "Cold Resistance" ] },
{ "name": "マグロック討伐", "en": "Kill a Igneo Talus", "types": [ "Rupee", "Gems", "Miniboss", "Talus", "Eldin" ] },
{ "name": "耐火の石兜", "en": "Flamebreaker Helm", "types": [ "Clothes", "Flame Gear", "Eldin", "Rupee" ] },
{ "name": "イチゴクレープ", "en": "Wildberry Crepe", "types": [ "Cooking", "Tabantha" ] },
{ "name": "ミニチャレンジ:宝石はお好き？", "en": "'Tools of the Trade' Side Quest", "types": [ "Side Quest", "Wasteland", "Gems" ] },
{ "name": "ミニチャレンジ:キールを探して！", "en": "'Find Kheel' Side Quest", "types": [ "Side Quest", "Tabantha" ] },
{ "name": "ミニチャレンジ:デスマウンテンの秘宝", "en": "'Death Mountain's Secret' Side Quest", "types": [ "Side Quest", "Eldin" ] },
{ "name": "ほこらチャレンジ:渦巻の中心へ", "en": "'Into the Vortex' Shrine Quest", "types": [ "Shrine", "Shrine Quest", "Akkala" ] },
{ "name": "ほこらチャレンジ:巨人三兄弟の秘密", "en": "'Three Giant Brothers' Shrine Quest", "types": [ "Shrine", "Shrine Quest", "Faron", "Hinox" ] },
{ "name": "ウツシエの記憶 3つ回収", "en": "Collect 3 Picture Memories", "types": [ "Camera" ] },
{ "name": "ハイラル図鑑 武器 5種登録", "en": "5 Equipment in Compendium", "types": [ "Camera", "Compendium" ] },
{ "name": "ビタロック+", "en": "Stasis +", "types": [ "Camera", "Rune Upgrade", "Hateno" ] },
{ "name": "がんばりの器 3つ入手", "en": "3 Stamina Vessels", "types": [ "Shrine", "Stamina" ] }
], [
{ "name": "コログのミ 30個", "en": "30 Koroks", "types": [ "Plateau Korok", "Central Hyrule Korok", "Hateno Korok", "Faron Korok", "Ridgeland Korok", "Lake Korok", "Wasteland Korok", "Woodland Korok", "Lanayru Korok", "Eldin Korok", "Akkala Korok", "Tabantha Korok", "Gerudo Korok", "Hebra Korok", "Dueling Peaks Korok" ] },
{ "name": "ヘブラの塔エリア コログのミ 9個", "en": "9 Hebra Koroks", "types": [ "Hebra Korok", "Hebra", "Cold Resistance" ] },
{ "name": "フィローネの塔エリア コログのミ 12個", "en": "12 Faron Koroks", "types": [ "Faron Korok", "Faron" ] },
{ "name": "タバンタの塔エリア コログのミ 12個", "en": "12 Tabantha Koroks", "types": [ "Tabantha Korok", "Tabantha" ] },
{ "name": "森林の塔エリア コログのミ 12個", "en": "12 Woodland Koroks", "types": [ "Woodland Korok", "Woodland" ] },
{ "name": "ラネールの塔エリア コログのミ 12個", "en": "12 Lanayru Koroks", "types": [ "Lanayru Korok", "Lanayru" ] },
{ "name": "双子山の塔エリア コログのミ 15個", "en": "15 Dueling Peaks Koroks", "types": [ "Dueling Peaks Korok", "Dueling Peaks" ] },
{ "name": "平原の塔エリア コログのミ 15個", "en": "15 Central Tower Koroks", "types": [ "Central Hyrule Korok", "Central Hyrule" ] },
{ "name": "英傑の服★", "en": "Champion's Tunic ★", "types": [ "Clothes", "Champion", "Camera", "Great Fairy" ] },
{ "name": "アッカレの塔エリア 祠3基", "en": "3 Akkala Shrines", "types": [ "Shrine", "Akkala" ] },
{ "name": "コハクの耳飾り", "en": "Amber Earrings", "types": [ "Clothes", "Gems", "Rupee", "Wasteland" ] },
{ "name": "ハイラル図鑑 生き物 5種登録", "en": "5 Creatures in Compendium", "types": [ "Camera", "Compendium" ] },
{ "name": "ハイラル図鑑 魔物 5種登録", "en": "5 Monsters in Compendium", "types": [ "Camera", "Compendium" ] },
{ "name": "リト防具一式", "en": "Full Snowquill Set", "types": [ "Clothes", "Snow Gear", "Cold Resistance", "Rupee", "Tabantha" ] },
{ "name": "オパールの耳飾り", "en": "Opal Earrings", "types": [ "Clothes", "Gems", "Rupee", "Wasteland" ] },
{ "name": "ほこらチャレンジ:孤島の試練", "en": "Akkala 'Trial of the Labyrinth' Shrine Quest", "types": [ "Shrine", "Shrine Quest", "Akkala", "Barbarian Gear" ] },
{ "name": "ほこらチャレンジ:ゴロンのど根性ガケ", "en": "'The Gut Check Challenge' Shrine Quest", "types": [ "Shrine", "Shrine Quest", "Eldin" ] },
{ "name": "ミニチャレンジ:免許皆伝への道", "en": "'The Road to Respect' Side Quest", "types": [ "Side Quest", "Eldin", "Talus" ] },
{ "name": "ミニチャレンジ:ライネル調査", "en": "'Lynel Safari' Side Quest", "types": [ "Side Quest", "Lanayru", "Camera", "Zora Gear" ] },
{ "name": "ミニチャレンジ:ぴかぴかのルミー しれん", "en": "'Legendary Rabbit Trial' Side Quest", "types": [ "Side Quest", "Wasteland", "Camera" ] },
{ "name": "ミニゲーム:飛行訓練 的を20個射抜く", "en": "20 Targets in Flight Range Minigame", "types": [ "Minigame", "Tabantha", "Cold Resistance" ] },
{ "name": "力の試練 極位のガーディアンを倒す", "en": "A Major Test of Strength Shrine of Killing the Guardian", "types": [ "Shrine", "Guardian" ] }
], [
{ "name": "アッカレの塔エリア コログのミ 12個", "en": "12 Akkala Koroks", "types": [ "Akkala Korok", "Akkala" ] },
{ "name": "ゲルドの塔エリア コログのミ 9個", "en": "9 Gerudo Koroks", "types": [ "Gerudo Korok", "Gerudo" ] },
{ "name": "ハテノ塔エリア コログのミ 15個", "en": "15 Hateno Koroks", "types": [ "Hateno Korok", "Hateno" ] },
{ "name": "湖の塔エリア コログのミ 15個", "en": "15 Lake Tower Koroks", "types": [ "Lake Korok", "Lake" ] },
{ "name": "丘陵の塔エリア コログのミ 15個", "en": "15 Ridgeland Koroks", "types": [ "Ridgeland Korok", "Ridgeland" ] },
{ "name": "オルディンの塔エリア コログのミ 12個", "en": "12 Eldin Koroks", "types": [ "Eldin Korok", "Eldin" ] },
{ "name": "英傑武器を作り直す", "en": "Remake a Champion's Weapon or Shield", "types": [ "Equipment", "Divine Beast", "Gems" ] },
{ "name": "ダイヤの頭飾り", "en": "Diamond Circlet", "types": [ "Clothes", "Gems", "Rupee", "Wasteland" ] },
{ "name": "耐火の石鎧★", "en": "Flamebreaker Armor ★", "types": [ "Clothes", "Flame Gear", "Eldin", "Rupee", "Great Fairy" ] },
{ "name": "耐火の石靴★", "en": "Flamebreaker Boots ★", "types": [ "Clothes", "Flame Gear", "Eldin", "Rupee", "Great Fairy" ] },
{ "name": "任意の熱砂シリーズ★", "en": "any Desert Voe Series ★", "types": [ "Clothes", "Desert Gear", "Wasteland", "Rupee", "Great Fairy" ] },
{ "name": "ミニチャレンジ:小さな妹の大きな願い", "en": "'Little Sister's Big Request' Side Quest", "types": [ "Side Quest", "Akkala" ] },
{ "name": "ミニチャレンジ:ブリザー谷のガチロック", "en": "'Face the Frost Talus' Side Quest", "types": [ "Side Quest", "Tabantha", "Hebra", "Cold Resistance" ] },
{ "name": "祠 11基攻略", "en": "11 Shrines", "types": [ "Shrine" ] },
{ "name": "ハイラル図鑑 武器 10種登録", "en": "10 Equipment in Compendium", "types": [ "Camera", "Compendium" ] },
{ "name": "モルドラジーク討伐", "en": "Kill a Molduga", "types": [ "Miniboss", "Molduga", "Wasteland" ] },
{ "name": "ほこらチャレンジ 5つ攻略", "en": "5 Shrine Quests", "types": [ "Shrine", "Shrine Quest" ] },
{ "name": "ほこらチャレンジ:力の泉の言い伝え", "en": "'The Spring of Power' Shrine Quest", "types": [ "Shrine", "Shrine Quest", "Akkala", "Dragon" ] },
{ "name": "“ライネルの”武器入手", "en": "Any 'Lynel' Equipment item", "types": [ "Equipment", "Lynel" ] },
{ "name": "シーカータワー 5基起動", "en": "Activate 5 Towers", "types": [ "Tower" ] }
], [
{ "name": "7つのエリアで祠を各1つ以上", "en": "1 Shrine in 7 Regions", "types": [ "Shrine" ] },
{ "name": "クライム防具一式", "en": "Full Climber's Set", "types": [ "Clothes", "Climbing Gear" ] },
{ "name": "ヘブラの塔エリア コログのミ 12個", "en": "12 Hebra Koroks", "types": [ "Hebra Korok", "Hebra", "Cold Resistance" ] },
{ "name": "フィローネの塔エリア コログのミ 15個", "en": "15 Faron Koroks", "types": [ "Faron Korok", "Faron" ] },
{ "name": "ラネールの塔エリア コログのミ 15個", "en": "15 Lanayru Koroks", "types": [ "Lanayru Korok", "Lanayru" ] },
{ "name": "ラバー防具一式", "en": "Full Rubber Set", "types": [ "Clothes", "Rubber Gear", "Faron", "Ridgeland" ] },
{ "name": "耐火の石兜★", "en": "Flamebreaker Helm ★", "types": [ "Clothes", "Flame Gear", "Eldin", "Rupee", "Great Fairy" ] },
{ "name": "ゾーラのすねあて★", "en": "Zora Greaves ★", "types": [ "Clothes", "Zora Gear", "Great Fairy", "Lizalfos", "Camera" ] },
{ "name": "ミニチャレンジ:モルドラジークの肝", "en": "'Medicinal Molduga' Side Quest", "types": [ "Side Quest", "Wasteland", "Molduga" ] },
{ "name": "ミニチャレンジ:解放 さらなる力", "en": "'Slated for Upgrades' Side Quest", "types": [ "Side Quest", "Hateno", "Camera" ] },
{ "name": "ミニチャレンジ:求ム！不審者情報", "en": "'A Shady Customer' Side Quest", "types": [ "Side Quest", "Akkala", "Kilton", "Camera" ] },
{ "name": "ミニチャレンジ:八人目の英雄", "en": "'The Eighth Heroine' Side Quest", "types": [ "Side Quest", "Wasteland", "Gerudo", "Boots", "Cold Resistance", "Camera" ] },
{ "name": "祠 12基攻略", "en": "12 Shrines", "types": [ "Shrine" ] },
{ "name": "ほこらチャレンジ:野生の試練", "en": "'Stranded on Eventide' Shrine Quest", "types": [ "Shrine", "Shrine Quest", "Faron" ] },
{ "name": "ほこらチャレンジ:ガーディアンを見たい！", "en": "'Guardian Slideshow' Shrine Quest", "types": [ "Shrine", "Shrine Quest", "Lake", "Camera", "Guardian" ] },
{ "name": "ほこらチャレンジ:ラネール山のお宝を探れ！", "en": "'The Spring of Wisdom' Shrine Quest", "types": [ "Shrine", "Shrine Quest", "Hateno", "Cold Resistance", "Dragon" ] },
{ "name": "山のヌシに乗る", "en": "Mount the Lord of the Mountain", "types": [ "Horse", "Ridgeland", "Stamina" ] },
{ "name": "ハイラル図鑑 生き物 10種登録", "en": "10 Creatures in Compendium", "types": [ "Camera", "Compendium" ] },
{ "name": "ハイラル図鑑 魔物 10種登録", "en": "10 Monsters in Compendium", "types": [ "Camera", "Compendium" ] }
], [
{ "name": "コログのミ 30個", "en": "30 Koroks", "types": [ "Plateau Korok", "Central Hyrule Korok", "Hateno Korok", "Faron Korok", "Ridgeland Korok", "Lake Korok", "Wasteland Korok", "Woodland Korok", "Lanayru Korok", "Eldin Korok", "Akkala Korok", "Tabantha Korok", "Gerudo Korok", "Hebra Korok", "Dueling Peaks Korok" ] },
{ "name": "ゲルドの塔エリア コログのミ 12個", "en": "12 Gerudo Koroks", "types": [ "Gerudo Korok", "Gerudo" ] },
{ "name": "アッカレの塔エリア コログのミ 15個", "en": "15 Akkala Koroks", "types": [ "Akkala Korok", "Akkala" ] },
{ "name": "荒野の塔エリア コログのミ 15個", "en": "15 Wasteland Koroks", "types": [ "Wasteland Korok", "Wasteland" ] },
{ "name": "タバンタの塔エリア コログのミ 15個", "en": "15 Tabantha Koroks", "types": [ "Tabantha Korok", "Tabantha" ] },
{ "name": "森林の塔エリア コログのミ 15個", "en": "15 Woodland Koroks", "types": [ "Woodland Korok", "Woodland" ] },
{ "name": "任意の夜光シリーズ★", "en": "any Radiant Series ★", "types": [ "Clothes", "Radiant Gear", "Rupee", "Gems", "Great Fairy" ] },
{ "name": "ボコブリンマスク", "en": "Bokoblin Mask", "types": [ "Clothes", "Kilton" ] },
{ "name": "コハクの耳飾り★", "en": "Amber Earrings ★", "types": [ "Clothes", "Gems", "Rupee", "Great Fairy" ] },
{ "name": "ミニチャレンジ:骨の馬の絵", "en": "'Stalhorse: Pictured!' Side Quest", "types": [ "Side Quest", "Hebra", "Camera" ] },
{ "name": "家を買う", "en": "Buy a House", "types": [ "Hateno", "Rupee" ] },
{ "name": "ハイラル図鑑 武器 15種登録", "en": "15 Equipment in Compendium", "types": [ "Camera", "Compendium" ] },
{ "name": "ほこらチャレンジ:弟はいずこ？", "en": "'Brother's Roast' Shrine Quest", "types": [ "Shrine", "Shrine Quest", "Eldin" ] },
{ "name": "シーカータワー 6基起動", "en": "Activate 6 Towers", "types": [ "Tower" ] }
], [
{ "name": "ハイラル図鑑 生き物 15種登録", "en": "15 Creatures in Compendium", "types": [ "Camera", "Compendium" ] },
{ "name": "ハイラル図鑑 魔物 15種登録", "en": "15 Monsters in Compendium", "types": [ "Camera", "Compendium" ] },
{ "name": "ゲルドの塔エリア コログのミ 15個", "en": "15 Gerudo Koroks", "types": [ "Gerudo Korok", "Gerudo" ] },
{ "name": "ヘブラの塔エリア コログのミ 15個", "en": "15 Hebra Koroks", "types": [ "Hebra Korok", "Hebra", "Cold Resistance" ] },
{ "name": "ゾーラ防具一式", "en": "Full Zora Set", "types": [ "Clothes", "Zora Gear", "Lanayru", "Camera" ] },
{ "name": "熱砂防具一式", "en": "Full Desert Voe Set", "types": [ "Clothes", "Desert Gear", "Wasteland", "Rupee" ] },
{ "name": "蛮族の兜★", "en": "Barbarian Helm ★", "types": [ "Clothes", "Barbarian Gear", "Great Fairy", "Lynel" ] },
{ "name": "蛮族の服★", "en": "Barbarian Armor ★", "types": [ "Clothes", "Barbarian Gear", "Great Fairy", "Lynel" ] },
{ "name": "スノーブーツ★", "en": "Snow Boots ★", "types": [ "Clothes", "Boots", "Side Quest", "Great Fairy", "Camera" ] },
{ "name": "トパーズの耳飾り★", "en": "Topaz Earrings ★", "types": [ "Clothes", "Gems", "Rupee", "Great Fairy" ] },
{ "name": "オパールの耳飾り★", "en": "Opal Earrings ★", "types": [ "Clothes", "Gems", "Rupee", "Great Fairy" ] },
{ "name": "ミニチャレンジ:宝石インポーター", "en": "'The Jewel Trade' Side Quest", "types": [ "Side Quest", "Eldin", "Gems" ] },
{ "name": "ほこらチャレンジ 6つ攻略", "en": "6 Shrine Quests", "types": [ "Shrine", "Shrine Quest" ] },
{ "name": "ほこらチャレンジ:盗まれた宝珠", "en": "'The Stolen Heirloom' Shrine Quest", "types": [ "Shrine", "Shrine Quest", "Dueling Peaks", "Heirloom", "Camera" ] },
{ "name": "メインチャレンジ:水の神獣ヴァ・ルッタ", "en": "'Divine Beast Vah Ruta' Main Quest", "types": [ "Divine Beast", "Lanayru" ] },
{ "name": "ウツシエの記憶 4つ回収", "en": "Collect 4 Picture Memories", "types": [ "Camera" ] },
{ "name": "ハート 計7個", "en": "7 Heart Containers", "types": [ "Shrine", "Heart" ] }
], [
{ "name": "ハイラル図鑑 武器 20種登録", "en": "20 Equipment in Compendium", "types": [ "Camera", "Compendium" ] },
{ "name": "大妖精 3人解放", "en": "Pay 3 Great Fairies", "types": [ "Rupee", "Great Fairy" ] },
{ "name": "耐火防具一式", "en": "Full Flamebreaker Set", "types": [ "Clothes", "Flame Gear", "Eldin", "Rupee" ] },
{ "name": "蛮族の腰巻き★", "en": "Barbarian Leg Wraps ★", "types": [ "Clothes", "Barbarian Gear", "Great Fairy", "Lynel" ] },
{ "name": "夜光防具一式", "en": "Full Radiant Set", "types": [ "Clothes", "Radiant Gear", "Rupee", "Gems", "Wasteland" ] },
{ "name": "サファイアの頭飾り★", "en": "Sapphire Circlet ★", "types": [ "Clothes", "Gems", "Rupee", "Great Fairy" ] },
{ "name": "ルビーの頭飾り★", "en": "Ruby Circlet ★", "types": [ "Clothes", "Gems", "Rupee", "Great Fairy" ] },
{ "name": "祠 13基攻略", "en": "13 Shrines", "types": [ "Shrine" ] },
{ "name": "ほこらチャレンジ 7つ攻略", "en": "7 Shrine Quests", "types": [ "Shrine", "Shrine Quest" ] },
{ "name": "ほこらチャレンジ:うるわしの美酒を求めて…", "en": "'The Perfect Drink' Shrine Quest", "types": [ "Shrine", "Shrine Quest", "Wastelands" ] },
{ "name": "ほこらチャレンジ:リトの兄弟岩", "en": "'Recital at Warbler's Nest' Shrine Quest", "types": [ "Shrine", "Shrine Quest", "Tabantha" ] },
{ "name": "ほこらチャレンジ:ドクロの左目", "en": "'The Skull's Eye' Shrine Quest", "types": [ "Shrine", "Shrine Quest", "Akkala" ] },
{ "name": "ほこらチャレンジ:リトの詩の謎", "en": "'The Ancient Rito Song' Shrine Quest", "types": [ "Shrine", "Shrine Quest", "Tabantha" ] },
{ "name": "ミニチャレンジ:もう一人の研究者", "en": "'Robbie's Research' Side Quest", "types": [ "Side Quest", "Akkala", "Camera" ] },
{ "name": "ウツシエの記憶 5つ回収", "en": "Collect 5 Picture Memories", "types": [ "Camera" ] },
{ "name": "ボヨーンハンマー", "en": "Spring-Loaded Hammer", "types": [ "Equipment", "Kilton" ] },
{ "name": "がんばりの器 4つ入手", "en": "4 Stamina Vessels", "types": [ "Shrine", "Stamina" ] },
{ "name": "シーカーストーン 全アイテム強化", "en": "Upgrade All Runes", "types": [ "Camera", "Rune Upgrade", "Hateno" ] },
{ "name": "ほこらチャレンジ:英傑祭の詩", "en": "'The Ceremonial Song' Shrine Quest", "types": [ "Shrine", "Shrine Quest", "Lanayru" ] }
], [
{ "name": "ハイラル図鑑 生き物 20種登録", "en": "20 Creatures in Compendium", "types": [ "Camera", "Compendium" ] },
{ "name": "ハイラル図鑑 魔物 20種登録", "en": "20 Monsters in Compendium", "types": [ "Camera", "Compendium" ] },
{ "name": "ミニチャレンジ:流された嫁", "en": "'A Wife Washed Away' Side Quest", "types": [ "Side Quest", "Lanayru" ] },
{ "name": "コログのミ 35個", "en": "35 Koroks", "types": [ "Plateau Korok", "Central Hyrule Korok", "Hateno Korok", "Faron Korok", "Ridgeland Korok", "Lake Korok", "Wasteland Korok", "Woodland Korok", "Lanayru Korok", "Eldin Korok", "Akkala Korok", "Tabantha Korok", "Gerudo Korok", "Hebra Korok", "Dueling Peaks Korok" ] },
{ "name": "ミニチャレンジ:忘れられた剣", "en": "'The Forgotten Sword' Side Quest", "types": [ "Side Quest", "Wasteland", "Gerudo", "Boots", "Cold Resistance", "Camera" ] },
{ "name": "ミニチャレンジ:ハイラルのなぞなぞしれん", "en": "'Riddles of Hyrule' Side Quest", "types": [ "Side Quest", "Woodland", "Lynel" ] },
{ "name": "ミニチャレンジ:雨ときどきカエル", "en": "'Frog Catching' Side Quest", "types": [ "Side Quest", "Lanayru" ] },
{ "name": "ミニチャレンジ:夜光石採集", "en": "'Luminous Stone Gathering' Side Quest", "types": [ "Side Quest", "Lanayru", "Gems" ] },
{ "name": "祠 14基攻略", "en": "14 Shrines", "types": [ "Shrine" ] },
{ "name": "ほこらチャレンジ 8つ攻略", "en": "8 Shrine Quests", "types": [ "Shrine", "Shrine Quest" ] },
{ "name": "シーカータワー 7基起動", "en": "Activate 7 Towers", "types": [ "Tower" ] }
], [
{ "name": "ミニチャレンジ:ラルス池の巨人討伐", "en": "'The Giant of Ralis Pond' Side Quest", "types": [ "Side Quest", "Lanayru", "Hinox" ] },
{ "name": "祠 15基攻略", "en": "15 Shrines", "types": [ "Shrine" ] },
{ "name": "メインチャレンジ:炎の神獣ヴァ・ルーダニア", "en": "'Divine Beast Vah Rudania' Main Quest", "types": [ "Divine Beast", "Eldin" ] },
{ "name": "ウツシエの記憶 6つ回収", "en": "Collect 6 Picture Memories", "types": [ "Camera" ] },
{ "name": "シーカータワー 8基起動", "en": "Activate 8 Towers", "types": [ "Tower" ] }
], [
{ "name": "祠 16基攻略", "en": "16 Shrines", "types": [ "Shrine" ] },
{ "name": "メインチャレンジ:雷の神獣ヴァ・ナボリス", "en": "'Divine Beast Vah Naboris' Main Quest", "types": [ "Divine Beast", "Wasteland" ] },
{ "name": "ガノン討伐", "en": "Beat Ganon", "types": [ "Hyrule Castle" ] },
{ "name": "シーカータワー 9基起動", "en": "Activate 9 Towers", "types": [ "Tower" ] }
], [
{ "name": "コログのミ 40個", "en": "40 Koroks", "types": [ "Plateau Korok", "Central Hyrule Korok", "Hateno Korok", "Faron Korok", "Ridgeland Korok", "Lake Korok", "Wasteland Korok", "Woodland Korok", "Lanayru Korok", "Eldin Korok", "Akkala Korok", "Tabantha Korok", "Gerudo Korok", "Hebra Korok", "Dueling Peaks Korok" ] },
{ "name": "ミニチャレンジ:巨大クジラの化石", "en": "'Leviathan Bones' Side Quest", "types": [ "Side Quest", "Camera" ] },
{ "name": "ミニチャレンジ:ゾーラの石碑を探して", "en": "'Zora Stone Monuments' Side Quest", "types": [ "Side Quest", "Lanayru" ] },
{ "name": "神獣系メインチャレンジ 2つ攻略", "en": "2 Divine Beast Main Quest", "types": [ "Divine Beast" ] },
{ "name": "ミニチャレンジ:バレッタを探して", "en": "'The Search for Barta' Side Quest", "types": [ "Side Quest", "Wasteland" ] },
{ "name": "ミニチャレンジ:犯人はだれだ！", "en": "'The Mystery Polluter' Side Quest", "types": [ "Side Quest", "Wasteland" ] },
{ "name": "ほこらチャレンジ:無敗の女王", "en": "'The Undefeated Champ' Shrine Quest", "types": [ "Shrine", "Shrine Quest", "Wastelands" ] },
{ "name": "シーカータワー 10基起動", "en": "Activate 10 Towers", "types": [ "Tower" ] },
{ "name": "ミニチャレンジ 15個攻略", "en": "15 Side Quests", "types": [ "Side Quest" ] },
{ "name": "蛮族防具一式", "en": "Full Barbarian Set", "types": [ "Clothes", "Barbarian Gear" ] }
]
];

//BotW_Bingo_Normal_v3 20 09 22

//@zdi6923
//@takuan_yellow
//@evolchronicle