var bingoList = [
[
{ "name": "レベル<br>1-A", "en": "Level<br>1-A", "types": [ "Level1", "ROW_A" ] },
{ "name": "レベル<br>1-B", "en": "Level<br>1-B", "types": [ "Level1", "ROW_B" ] },
{ "name": "レベル<br>1-C", "en": "Level<br>1-C", "types": [ "Level1", "ROW_C" ] },
{ "name": "レベル<br>1-D", "en": "Level<br>1-D", "types": [ "Level1", "ROW_D" ] },
{ "name": "レベル<br>1-E", "en": "Level<br>1-E", "types": [ "Level1", "ROW_E" ] },
{ "name": "レベル<br>1-F", "en": "Level<br>1-F", "types": [ "Level1", "ROW_F" ] },
{ "name": "レベル<br>1-G", "en": "Level<br>1-G", "types": [ "Level1", "ROW_G" ] },
{ "name": "レベル<br>1-H", "en": "Level<br>1-H", "types": [ "Level1", "ROW_H" ] },
{ "name": "レベル<br>1-I", "en": "Level<br>1-I", "types": [ "Level1", "ROW_I" ] },
{ "name": "レベル<br>1-J", "en": "Level<br>1-J", "types": [ "Level1", "ROW_J" ] }
],[
{ "name": "レベル<br>2-A", "en": "Level<br>2-A", "types": [ "Level2", "ROW_A" ] },
{ "name": "レベル<br>2-B", "en": "Level<br>2-B", "types": [ "Level2", "ROW_B" ] },
{ "name": "レベル<br>2-C", "en": "Level<br>2-C", "types": [ "Level2", "ROW_C" ] },
{ "name": "レベル<br>2-D", "en": "Level<br>2-D", "types": [ "Level2", "ROW_D" ] },
{ "name": "レベル<br>2-E", "en": "Level<br>2-E", "types": [ "Level2", "ROW_E" ] },
{ "name": "レベル<br>2-F", "en": "Level<br>2-F", "types": [ "Level2", "ROW_F" ] },
{ "name": "レベル<br>2-G", "en": "Level<br>2-G", "types": [ "Level2", "ROW_G" ] },
{ "name": "レベル<br>2-H", "en": "Level<br>2-H", "types": [ "Level2", "ROW_H" ] },
{ "name": "レベル<br>2-I", "en": "Level<br>2-I", "types": [ "Level2", "ROW_I" ] },
{ "name": "レベル<br>2-J", "en": "Level<br>2-J", "types": [ "Level2", "ROW_J" ] }
],
[
{ "name": "レベル<br>3-A", "en": "Level<br>3-A", "types": [ "Level3", "ROW_A" ] },
{ "name": "レベル<br>3-B", "en": "Level<br>3-B", "types": [ "Level3", "ROW_B" ] },
{ "name": "レベル<br>3-C", "en": "Level<br>3-C", "types": [ "Level3", "ROW_C" ] },
{ "name": "レベル<br>3-D", "en": "Level<br>3-D", "types": [ "Level3", "ROW_D" ] },
{ "name": "レベル<br>3-E", "en": "Level<br>3-E", "types": [ "Level3", "ROW_E" ] },
{ "name": "レベル<br>3-F", "en": "Level<br>3-F", "types": [ "Level3", "ROW_F" ] },
{ "name": "レベル<br>3-G", "en": "Level<br>3-G", "types": [ "Level3", "ROW_G" ] },
{ "name": "レベル<br>3-H", "en": "Level<br>3-H", "types": [ "Level3", "ROW_H" ] },
{ "name": "レベル<br>3-I", "en": "Level<br>3-I", "types": [ "Level3", "ROW_I" ] },
{ "name": "レベル<br>3-J", "en": "Level<br>3-J", "types": [ "Level3", "ROW_J" ] }
],
[
{ "name": "レベル<br>4-A", "en": "Level<br>4-A", "types": [ "Level4", "ROW_A" ] },
{ "name": "レベル<br>4-B", "en": "Level<br>4-B", "types": [ "Level4", "ROW_B" ] },
{ "name": "レベル<br>4-C", "en": "Level<br>4-C", "types": [ "Level4", "ROW_C" ] },
{ "name": "レベル<br>4-D", "en": "Level<br>4-D", "types": [ "Level4", "ROW_D" ] },
{ "name": "レベル<br>4-E", "en": "Level<br>4-E", "types": [ "Level4", "ROW_E" ] },
{ "name": "レベル<br>4-F", "en": "Level<br>4-F", "types": [ "Level4", "ROW_F" ] },
{ "name": "レベル<br>4-G", "en": "Level<br>4-G", "types": [ "Level4", "ROW_G" ] },
{ "name": "レベル<br>4-H", "en": "Level<br>4-H", "types": [ "Level4", "ROW_H" ] },
{ "name": "レベル<br>4-I", "en": "Level<br>4-I", "types": [ "Level4", "ROW_I" ] },
{ "name": "レベル<br>4-J", "en": "Level<br>4-J", "types": [ "Level4", "ROW_J" ] }
],
[
{ "name": "レベル<br>5-A", "en": "Level<br>5-A", "types": [ "Level5", "ROW_A" ] },
{ "name": "レベル<br>5-B", "en": "Level<br>5-B", "types": [ "Level5", "ROW_B" ] },
{ "name": "レベル<br>5-C", "en": "Level<br>5-C", "types": [ "Level5", "ROW_C" ] },
{ "name": "レベル<br>5-D", "en": "Level<br>5-D", "types": [ "Level5", "ROW_D" ] },
{ "name": "レベル<br>5-E", "en": "Level<br>5-E", "types": [ "Level5", "ROW_E" ] },
{ "name": "レベル<br>5-F", "en": "Level<br>5-F", "types": [ "Level5", "ROW_F" ] },
{ "name": "レベル<br>5-G", "en": "Level<br>5-G", "types": [ "Level5", "ROW_G" ] },
{ "name": "レベル<br>5-H", "en": "Level<br>5-H", "types": [ "Level5", "ROW_H" ] },
{ "name": "レベル<br>5-I", "en": "Level<br>5-I", "types": [ "Level5", "ROW_I" ] },
{ "name": "レベル<br>5-J", "en": "Level<br>5-J", "types": [ "Level5", "ROW_J" ] }
],
[
{ "name": "レベル<br>6-A", "en": "Level<br>6-A", "types": [ "Level6", "ROW_A" ] },
{ "name": "レベル<br>6-B", "en": "Level<br>6-B", "types": [ "Level6", "ROW_B" ] },
{ "name": "レベル<br>6-C", "en": "Level<br>6-C", "types": [ "Level6", "ROW_C" ] },
{ "name": "レベル<br>6-D", "en": "Level<br>6-D", "types": [ "Level6", "ROW_D" ] },
{ "name": "レベル<br>6-E", "en": "Level<br>6-E", "types": [ "Level6", "ROW_E" ] },
{ "name": "レベル<br>6-F", "en": "Level<br>6-F", "types": [ "Level6", "ROW_F" ] },
{ "name": "レベル<br>6-G", "en": "Level<br>6-G", "types": [ "Level6", "ROW_G" ] },
{ "name": "レベル<br>6-H", "en": "Level<br>6-H", "types": [ "Level6", "ROW_H" ] },
{ "name": "レベル<br>6-I", "en": "Level<br>6-I", "types": [ "Level6", "ROW_I" ] },
{ "name": "レベル<br>6-J", "en": "Level<br>6-J", "types": [ "Level6", "ROW_J" ] }
],
[
{ "name": "レベル<br>7-A", "en": "Level<br>7-A", "types": [ "Level7", "ROW_A" ] },
{ "name": "レベル<br>7-B", "en": "Level<br>7-B", "types": [ "Level7", "ROW_B" ] },
{ "name": "レベル<br>7-C", "en": "Level<br>7-C", "types": [ "Level7", "ROW_C" ] },
{ "name": "レベル<br>7-D", "en": "Level<br>7-D", "types": [ "Level7", "ROW_D" ] },
{ "name": "レベル<br>7-E", "en": "Level<br>7-E", "types": [ "Level7", "ROW_E" ] },
{ "name": "レベル<br>7-F", "en": "Level<br>7-F", "types": [ "Level7", "ROW_F" ] },
{ "name": "レベル<br>7-G", "en": "Level<br>7-G", "types": [ "Level7", "ROW_G" ] },
{ "name": "レベル<br>7-H", "en": "Level<br>7-H", "types": [ "Level7", "ROW_H" ] },
{ "name": "レベル<br>7-I", "en": "Level<br>7-I", "types": [ "Level7", "ROW_I" ] },
{ "name": "レベル<br>7-J", "en": "Level<br>7-J", "types": [ "Level7", "ROW_J" ] }
],
[
{ "name": "レベル<br>8-A", "en": "Level<br>8-A", "types": [ "Level8", "ROW_A" ] },
{ "name": "レベル<br>8-B", "en": "Level<br>8-B", "types": [ "Level8", "ROW_B" ] },
{ "name": "レベル<br>8-C", "en": "Level<br>8-C", "types": [ "Level8", "ROW_C" ] },
{ "name": "レベル<br>8-D", "en": "Level<br>8-D", "types": [ "Level8", "ROW_D" ] },
{ "name": "レベル<br>8-E", "en": "Level<br>8-E", "types": [ "Level8", "ROW_E" ] },
{ "name": "レベル<br>8-F", "en": "Level<br>8-F", "types": [ "Level8", "ROW_F" ] },
{ "name": "レベル<br>8-G", "en": "Level<br>8-G", "types": [ "Level8", "ROW_G" ] },
{ "name": "レベル<br>8-H", "en": "Level<br>8-H", "types": [ "Level8", "ROW_H" ] },
{ "name": "レベル<br>8-I", "en": "Level<br>8-I", "types": [ "Level8", "ROW_I" ] },
{ "name": "レベル<br>8-J", "en": "Level<br>8-J", "types": [ "Level8", "ROW_J" ] }
],
[
{ "name": "レベル<br>9-A", "en": "Level<br>9-A", "types": [ "Level9", "ROW_A" ] },
{ "name": "レベル<br>9-B", "en": "Level<br>9-B", "types": [ "Level9", "ROW_B" ] },
{ "name": "レベル<br>9-C", "en": "Level<br>9-C", "types": [ "Level9", "ROW_C" ] },
{ "name": "レベル<br>9-D", "en": "Level<br>9-D", "types": [ "Level9", "ROW_D" ] },
{ "name": "レベル<br>9-E", "en": "Level<br>9-E", "types": [ "Level9", "ROW_E" ] },
{ "name": "レベル<br>9-F", "en": "Level<br>9-F", "types": [ "Level9", "ROW_F" ] },
{ "name": "レベル<br>9-G", "en": "Level<br>9-G", "types": [ "Level9", "ROW_G" ] },
{ "name": "レベル<br>9-H", "en": "Level<br>9-H", "types": [ "Level9", "ROW_H" ] },
{ "name": "レベル<br>9-I", "en": "Level<br>9-I", "types": [ "Level9", "ROW_I" ] },
{ "name": "レベル<br>9-J", "en": "Level<br>9-J", "types": [ "Level9", "ROW_J" ] }
],
[
{ "name": "レベル<br>10-A", "en": "Level<br>10-A", "types": [ "Level10", "ROW_A" ] },
{ "name": "レベル<br>10-B", "en": "Level<br>10-B", "types": [ "Level10", "ROW_B" ] },
{ "name": "レベル<br>10-C", "en": "Level<br>10-C", "types": [ "Level10", "ROW_C" ] },
{ "name": "レベル<br>10-D", "en": "Level<br>10-D", "types": [ "Level10", "ROW_D" ] },
{ "name": "レベル<br>10-E", "en": "Level<br>10-E", "types": [ "Level10", "ROW_E" ] },
{ "name": "レベル<br>10-F", "en": "Level<br>10-F", "types": [ "Level10", "ROW_F" ] },
{ "name": "レベル<br>10-G", "en": "Level<br>10-G", "types": [ "Level10", "ROW_G" ] },
{ "name": "レベル<br>10-H", "en": "Level<br>10-H", "types": [ "Level10", "ROW_H" ] },
{ "name": "レベル<br>10-I", "en": "Level<br>10-I", "types": [ "Level10", "ROW_I" ] },
{ "name": "レベル<br>10-J", "en": "Level<br>10-J", "types": [ "Level10", "ROW_J" ] }
],
[
{ "name": "レベル<br>11-A", "en": "Level<br>11-A", "types": [ "Level11", "ROW_A" ] },
{ "name": "レベル<br>11-B", "en": "Level<br>11-B", "types": [ "Level11", "ROW_B" ] },
{ "name": "レベル<br>11-C", "en": "Level<br>11-C", "types": [ "Level11", "ROW_C" ] },
{ "name": "レベル<br>11-D", "en": "Level<br>11-D", "types": [ "Level11", "ROW_D" ] },
{ "name": "レベル<br>11-E", "en": "Level<br>11-E", "types": [ "Level11", "ROW_E" ] },
{ "name": "レベル<br>11-F", "en": "Level<br>11-F", "types": [ "Level11", "ROW_F" ] },
{ "name": "レベル<br>11-G", "en": "Level<br>11-G", "types": [ "Level11", "ROW_G" ] },
{ "name": "レベル<br>11-H", "en": "Level<br>11-H", "types": [ "Level11", "ROW_H" ] },
{ "name": "レベル<br>11-I", "en": "Level<br>11-I", "types": [ "Level11", "ROW_I" ] },
{ "name": "レベル<br>11-J", "en": "Level<br>11-J", "types": [ "Level11", "ROW_J" ] }
],
[
{ "name": "レベル<br>12-A", "en": "Level<br>12-A", "types": [ "Level12", "ROW_A" ] },
{ "name": "レベル<br>12-B", "en": "Level<br>12-B", "types": [ "Level12", "ROW_B" ] },
{ "name": "レベル<br>12-C", "en": "Level<br>12-C", "types": [ "Level12", "ROW_C" ] },
{ "name": "レベル<br>12-D", "en": "Level<br>12-D", "types": [ "Level12", "ROW_D" ] },
{ "name": "レベル<br>12-E", "en": "Level<br>12-E", "types": [ "Level12", "ROW_E" ] },
{ "name": "レベル<br>12-F", "en": "Level<br>12-F", "types": [ "Level12", "ROW_F" ] },
{ "name": "レベル<br>12-G", "en": "Level<br>12-G", "types": [ "Level12", "ROW_G" ] },
{ "name": "レベル<br>12-H", "en": "Level<br>12-H", "types": [ "Level12", "ROW_H" ] },
{ "name": "レベル<br>12-I", "en": "Level<br>12-I", "types": [ "Level12", "ROW_I" ] },
{ "name": "レベル<br>12-J", "en": "Level<br>12-J", "types": [ "Level12", "ROW_J" ] }
],
[
{ "name": "レベル<br>13-A", "en": "Level<br>13-A", "types": [ "Level13", "ROW_A" ] },
{ "name": "レベル<br>13-B", "en": "Level<br>13-B", "types": [ "Level13", "ROW_B" ] },
{ "name": "レベル<br>13-C", "en": "Level<br>13-C", "types": [ "Level13", "ROW_C" ] },
{ "name": "レベル<br>13-D", "en": "Level<br>13-D", "types": [ "Level13", "ROW_D" ] },
{ "name": "レベル<br>13-E", "en": "Level<br>13-E", "types": [ "Level13", "ROW_E" ] },
{ "name": "レベル<br>13-F", "en": "Level<br>13-F", "types": [ "Level13", "ROW_F" ] },
{ "name": "レベル<br>13-G", "en": "Level<br>13-G", "types": [ "Level13", "ROW_G" ] },
{ "name": "レベル<br>13-H", "en": "Level<br>13-H", "types": [ "Level13", "ROW_H" ] },
{ "name": "レベル<br>13-I", "en": "Level<br>13-I", "types": [ "Level13", "ROW_I" ] },
{ "name": "レベル<br>13-J", "en": "Level<br>13-J", "types": [ "Level13", "ROW_J" ] }
],
[
{ "name": "レベル<br>14-A", "en": "Level<br>14-A", "types": [ "Level14", "ROW_A" ] },
{ "name": "レベル<br>14-B", "en": "Level<br>14-B", "types": [ "Level14", "ROW_B" ] },
{ "name": "レベル<br>14-C", "en": "Level<br>14-C", "types": [ "Level14", "ROW_C" ] },
{ "name": "レベル<br>14-D", "en": "Level<br>14-D", "types": [ "Level14", "ROW_D" ] },
{ "name": "レベル<br>14-E", "en": "Level<br>14-E", "types": [ "Level14", "ROW_E" ] },
{ "name": "レベル<br>14-F", "en": "Level<br>14-F", "types": [ "Level14", "ROW_F" ] },
{ "name": "レベル<br>14-G", "en": "Level<br>14-G", "types": [ "Level14", "ROW_G" ] },
{ "name": "レベル<br>14-H", "en": "Level<br>14-H", "types": [ "Level14", "ROW_H" ] },
{ "name": "レベル<br>14-I", "en": "Level<br>14-I", "types": [ "Level14", "ROW_I" ] },
{ "name": "レベル<br>14-J", "en": "Level<br>14-J", "types": [ "Level14", "ROW_J" ] }
],
[
{ "name": "レベル<br>15-A", "en": "Level<br>15-A", "types": [ "Level15", "ROW_A" ] },
{ "name": "レベル<br>15-B", "en": "Level<br>15-B", "types": [ "Level15", "ROW_B" ] },
{ "name": "レベル<br>15-C", "en": "Level<br>15-C", "types": [ "Level15", "ROW_C" ] },
{ "name": "レベル<br>15-D", "en": "Level<br>15-D", "types": [ "Level15", "ROW_D" ] },
{ "name": "レベル<br>15-E", "en": "Level<br>15-E", "types": [ "Level15", "ROW_E" ] },
{ "name": "レベル<br>15-F", "en": "Level<br>15-F", "types": [ "Level15", "ROW_F" ] },
{ "name": "レベル<br>15-G", "en": "Level<br>15-G", "types": [ "Level15", "ROW_G" ] },
{ "name": "レベル<br>15-H", "en": "Level<br>15-H", "types": [ "Level15", "ROW_H" ] },
{ "name": "レベル<br>15-I", "en": "Level<br>15-I", "types": [ "Level15", "ROW_I" ] },
{ "name": "レベル<br>15-J", "en": "Level<br>15-J", "types": [ "Level15", "ROW_J" ] }
],
[
{ "name": "レベル<br>16-A", "en": "Level<br>16-A", "types": [ "Level16", "ROW_A" ] },
{ "name": "レベル<br>16-B", "en": "Level<br>16-B", "types": [ "Level16", "ROW_B" ] },
{ "name": "レベル<br>16-C", "en": "Level<br>16-C", "types": [ "Level16", "ROW_C" ] },
{ "name": "レベル<br>16-D", "en": "Level<br>16-D", "types": [ "Level16", "ROW_D" ] },
{ "name": "レベル<br>16-E", "en": "Level<br>16-E", "types": [ "Level16", "ROW_E" ] },
{ "name": "レベル<br>16-F", "en": "Level<br>16-F", "types": [ "Level16", "ROW_F" ] },
{ "name": "レベル<br>16-G", "en": "Level<br>16-G", "types": [ "Level16", "ROW_G" ] },
{ "name": "レベル<br>16-H", "en": "Level<br>16-H", "types": [ "Level16", "ROW_H" ] },
{ "name": "レベル<br>16-I", "en": "Level<br>16-I", "types": [ "Level16", "ROW_I" ] },
{ "name": "レベル<br>16-J", "en": "Level<br>16-J", "types": [ "Level16", "ROW_J" ] }
],
[
{ "name": "レベル<br>17-A", "en": "Level<br>17-A", "types": [ "Level17", "ROW_A" ] },
{ "name": "レベル<br>17-B", "en": "Level<br>17-B", "types": [ "Level17", "ROW_B" ] },
{ "name": "レベル<br>17-C", "en": "Level<br>17-C", "types": [ "Level17", "ROW_C" ] },
{ "name": "レベル<br>17-D", "en": "Level<br>17-D", "types": [ "Level17", "ROW_D" ] },
{ "name": "レベル<br>17-E", "en": "Level<br>17-E", "types": [ "Level17", "ROW_E" ] },
{ "name": "レベル<br>17-F", "en": "Level<br>17-F", "types": [ "Level17", "ROW_F" ] },
{ "name": "レベル<br>17-G", "en": "Level<br>17-G", "types": [ "Level17", "ROW_G" ] },
{ "name": "レベル<br>17-H", "en": "Level<br>17-H", "types": [ "Level17", "ROW_H" ] },
{ "name": "レベル<br>17-I", "en": "Level<br>17-I", "types": [ "Level17", "ROW_I" ] },
{ "name": "レベル<br>17-J", "en": "Level<br>17-J", "types": [ "Level17", "ROW_J" ] }
],
[
{ "name": "レベル<br>18-A", "en": "Level<br>18-A", "types": [ "Level18", "ROW_A" ] },
{ "name": "レベル<br>18-B", "en": "Level<br>18-B", "types": [ "Level18", "ROW_B" ] },
{ "name": "レベル<br>18-C", "en": "Level<br>18-C", "types": [ "Level18", "ROW_C" ] },
{ "name": "レベル<br>18-D", "en": "Level<br>18-D", "types": [ "Level18", "ROW_D" ] },
{ "name": "レベル<br>18-E", "en": "Level<br>18-E", "types": [ "Level18", "ROW_E" ] },
{ "name": "レベル<br>18-F", "en": "Level<br>18-F", "types": [ "Level18", "ROW_F" ] },
{ "name": "レベル<br>18-G", "en": "Level<br>18-G", "types": [ "Level18", "ROW_G" ] },
{ "name": "レベル<br>18-H", "en": "Level<br>18-H", "types": [ "Level18", "ROW_H" ] },
{ "name": "レベル<br>18-I", "en": "Level<br>18-I", "types": [ "Level18", "ROW_I" ] },
{ "name": "レベル<br>18-J", "en": "Level<br>18-J", "types": [ "Level18", "ROW_J" ] }
],
[
{ "name": "レベル<br>19-A", "en": "Level<br>19-A", "types": [ "Level19", "ROW_A" ] },
{ "name": "レベル<br>19-B", "en": "Level<br>19-B", "types": [ "Level19", "ROW_B" ] },
{ "name": "レベル<br>19-C", "en": "Level<br>19-C", "types": [ "Level19", "ROW_C" ] },
{ "name": "レベル<br>19-D", "en": "Level<br>19-D", "types": [ "Level19", "ROW_D" ] },
{ "name": "レベル<br>19-E", "en": "Level<br>19-E", "types": [ "Level19", "ROW_E" ] },
{ "name": "レベル<br>19-F", "en": "Level<br>19-F", "types": [ "Level19", "ROW_F" ] },
{ "name": "レベル<br>19-G", "en": "Level<br>19-G", "types": [ "Level19", "ROW_G" ] },
{ "name": "レベル<br>19-H", "en": "Level<br>19-H", "types": [ "Level19", "ROW_H" ] },
{ "name": "レベル<br>19-I", "en": "Level<br>19-I", "types": [ "Level19", "ROW_I" ] },
{ "name": "レベル<br>19-J", "en": "Level<br>19-J", "types": [ "Level19", "ROW_J" ] }
],
[
{ "name": "レベル<br>20-A", "en": "Level<br>20-A", "types": [ "Level20", "ROW_A" ] },
{ "name": "レベル<br>20-B", "en": "Level<br>20-B", "types": [ "Level20", "ROW_B" ] },
{ "name": "レベル<br>20-C", "en": "Level<br>20-C", "types": [ "Level20", "ROW_C" ] },
{ "name": "レベル<br>20-D", "en": "Level<br>20-D", "types": [ "Level20", "ROW_D" ] },
{ "name": "レベル<br>20-E", "en": "Level<br>20-E", "types": [ "Level20", "ROW_E" ] },
{ "name": "レベル<br>20-F", "en": "Level<br>20-F", "types": [ "Level20", "ROW_F" ] },
{ "name": "レベル<br>20-G", "en": "Level<br>20-G", "types": [ "Level20", "ROW_G" ] },
{ "name": "レベル<br>20-H", "en": "Level<br>20-H", "types": [ "Level20", "ROW_H" ] },
{ "name": "レベル<br>20-I", "en": "Level<br>20-I", "types": [ "Level20", "ROW_I" ] },
{ "name": "レベル<br>20-J", "en": "Level<br>20-J", "types": [ "Level20", "ROW_J" ] }
],
[
{ "name": "レベル<br>21-A", "en": "Level<br>21-A", "types": [ "Level21", "ROW_A" ] },
{ "name": "レベル<br>21-B", "en": "Level<br>21-B", "types": [ "Level21", "ROW_B" ] },
{ "name": "レベル<br>21-C", "en": "Level<br>21-C", "types": [ "Level21", "ROW_C" ] },
{ "name": "レベル<br>21-D", "en": "Level<br>21-D", "types": [ "Level21", "ROW_D" ] },
{ "name": "レベル<br>21-E", "en": "Level<br>21-E", "types": [ "Level21", "ROW_E" ] },
{ "name": "レベル<br>21-F", "en": "Level<br>21-F", "types": [ "Level21", "ROW_F" ] },
{ "name": "レベル<br>21-G", "en": "Level<br>21-G", "types": [ "Level21", "ROW_G" ] },
{ "name": "レベル<br>21-H", "en": "Level<br>21-H", "types": [ "Level21", "ROW_H" ] },
{ "name": "レベル<br>21-I", "en": "Level<br>21-I", "types": [ "Level21", "ROW_I" ] },
{ "name": "レベル<br>21-J", "en": "Level<br>21-J", "types": [ "Level21", "ROW_J" ] }
],
[
{ "name": "レベル<br>22-A", "en": "Level<br>22-A", "types": [ "Level22", "ROW_A" ] },
{ "name": "レベル<br>22-B", "en": "Level<br>22-B", "types": [ "Level22", "ROW_B" ] },
{ "name": "レベル<br>22-C", "en": "Level<br>22-C", "types": [ "Level22", "ROW_C" ] },
{ "name": "レベル<br>22-D", "en": "Level<br>22-D", "types": [ "Level22", "ROW_D" ] },
{ "name": "レベル<br>22-E", "en": "Level<br>22-E", "types": [ "Level22", "ROW_E" ] },
{ "name": "レベル<br>22-F", "en": "Level<br>22-F", "types": [ "Level22", "ROW_F" ] },
{ "name": "レベル<br>22-G", "en": "Level<br>22-G", "types": [ "Level22", "ROW_G" ] },
{ "name": "レベル<br>22-H", "en": "Level<br>22-H", "types": [ "Level22", "ROW_H" ] },
{ "name": "レベル<br>22-I", "en": "Level<br>22-I", "types": [ "Level22", "ROW_I" ] },
{ "name": "レベル<br>22-J", "en": "Level<br>22-J", "types": [ "Level22", "ROW_J" ] }
],
[
{ "name": "レベル<br>23-A", "en": "Level<br>23-A", "types": [ "Level23", "ROW_A" ] },
{ "name": "レベル<br>23-B", "en": "Level<br>23-B", "types": [ "Level23", "ROW_B" ] },
{ "name": "レベル<br>23-C", "en": "Level<br>23-C", "types": [ "Level23", "ROW_C" ] },
{ "name": "レベル<br>23-D", "en": "Level<br>23-D", "types": [ "Level23", "ROW_D" ] },
{ "name": "レベル<br>23-E", "en": "Level<br>23-E", "types": [ "Level23", "ROW_E" ] },
{ "name": "レベル<br>23-F", "en": "Level<br>23-F", "types": [ "Level23", "ROW_F" ] },
{ "name": "レベル<br>23-G", "en": "Level<br>23-G", "types": [ "Level23", "ROW_G" ] },
{ "name": "レベル<br>23-H", "en": "Level<br>23-H", "types": [ "Level23", "ROW_H" ] },
{ "name": "レベル<br>23-I", "en": "Level<br>23-I", "types": [ "Level23", "ROW_I" ] },
{ "name": "レベル<br>23-J", "en": "Level<br>23-J", "types": [ "Level23", "ROW_J" ] }
],
[
{ "name": "レベル<br>24-A", "en": "Level<br>24-A", "types": [ "Level24", "ROW_A" ] },
{ "name": "レベル<br>24-B", "en": "Level<br>24-B", "types": [ "Level24", "ROW_B" ] },
{ "name": "レベル<br>24-C", "en": "Level<br>24-C", "types": [ "Level24", "ROW_C" ] },
{ "name": "レベル<br>24-D", "en": "Level<br>24-D", "types": [ "Level24", "ROW_D" ] },
{ "name": "レベル<br>24-E", "en": "Level<br>24-E", "types": [ "Level24", "ROW_E" ] },
{ "name": "レベル<br>24-F", "en": "Level<br>24-F", "types": [ "Level24", "ROW_F" ] },
{ "name": "レベル<br>24-G", "en": "Level<br>24-G", "types": [ "Level24", "ROW_G" ] },
{ "name": "レベル<br>24-H", "en": "Level<br>24-H", "types": [ "Level24", "ROW_H" ] },
{ "name": "レベル<br>24-I", "en": "Level<br>24-I", "types": [ "Level24", "ROW_I" ] },
{ "name": "レベル<br>24-J", "en": "Level<br>24-J", "types": [ "Level24", "ROW_J" ] }
],
[
{ "name": "レベル<br>25-A", "en": "Level<br>25-A", "types": [ "Level25", "ROW_A" ] },
{ "name": "レベル<br>25-B", "en": "Level<br>25-B", "types": [ "Level25", "ROW_B" ] },
{ "name": "レベル<br>25-C", "en": "Level<br>25-C", "types": [ "Level25", "ROW_C" ] },
{ "name": "レベル<br>25-D", "en": "Level<br>25-D", "types": [ "Level25", "ROW_D" ] },
{ "name": "レベル<br>25-E", "en": "Level<br>25-E", "types": [ "Level25", "ROW_E" ] },
{ "name": "レベル<br>25-F", "en": "Level<br>25-F", "types": [ "Level25", "ROW_F" ] },
{ "name": "レベル<br>25-G", "en": "Level<br>25-G", "types": [ "Level25", "ROW_G" ] },
{ "name": "レベル<br>25-H", "en": "Level<br>25-H", "types": [ "Level25", "ROW_H" ] },
{ "name": "レベル<br>25-I", "en": "Level<br>25-I", "types": [ "Level25", "ROW_I" ] },
{ "name": "レベル<br>25-J", "en": "Level<br>25-J", "types": [ "Level25", "ROW_J" ] }
]
];
